package com.keykii.neo;

final class RemoteFontCatalog {
    static final int FIRST_STYLE = 1000;
    static final int FREE_AD_COUNT = 320;
    static final int PRO_COUNT = 704;
    static final String GOOGLE_FONTS_REV = "23e54b51ddffbc7713c583748e3bd86f62b1fa4a";

    static final class Entry {
        final int style;
        final String name;
        final String path;
        final boolean pro;

        Entry(int style, String name, String path, boolean pro) {
            this.style = style;
            this.name = name;
            this.path = path;
            this.pro = pro;
        }
    }

    static final Entry[] ITEMS = new Entry[] {
        new Entry(1000, "Abel", "ofl/abel/Abel-Regular.ttf", false),
        new Entry(1001, "Abhaya Libre", "ofl/abhayalibre/AbhayaLibre-Regular.ttf", false),
        new Entry(1002, "Aboreto", "ofl/aboreto/Aboreto-Regular.ttf", false),
        new Entry(1003, "Abyssinica SIL", "ofl/abyssinicasil/AbyssinicaSIL-Regular.ttf", false),
        new Entry(1004, "Acme", "ofl/acme/Acme-Regular.ttf", false),
        new Entry(1005, "Actor", "ofl/actor/Actor-Regular.ttf", false),
        new Entry(1006, "Adamina", "ofl/adamina/Adamina-Regular.ttf", false),
        new Entry(1007, "Adobe Blank", "ofl/adobeblank/AdobeBlank-Regular.ttf", false),
        new Entry(1008, "Advent Pro", "ofl/adventpro/AdventPro[wdth,wght].ttf", false),
        new Entry(1009, "Agbalumo", "ofl/agbalumo/Agbalumo-Regular.ttf", false),
        new Entry(1010, "Agu Display", "ofl/agudisplay/AguDisplay[MORF].ttf", false),
        new Entry(1011, "Akatab", "ofl/akatab/Akatab-Regular.ttf", false),
        new Entry(1012, "Akronim", "ofl/akronim/Akronim-Regular.ttf", false),
        new Entry(1013, "Aksara Bali Galang", "ofl/aksarabaligalang/AksaraBaliGalang-Regular.ttf", false),
        new Entry(1014, "Aladin", "ofl/aladin/Aladin-Regular.ttf", false),
        new Entry(1015, "Alan Sans", "ofl/alansans/AlanSans[wght].ttf", false),
        new Entry(1016, "Alatsi", "ofl/alatsi/Alatsi-Regular.ttf", false),
        new Entry(1017, "Alef", "ofl/alef/Alef-Regular.ttf", false),
        new Entry(1018, "Alegreya", "ofl/alegreya/Alegreya[wght].ttf", false),
        new Entry(1019, "Alegreya SC", "ofl/alegreyasc/AlegreyaSC-Regular.ttf", false),
        new Entry(1020, "Alfa Slab One", "ofl/alfaslabone/AlfaSlabOne-Regular.ttf", false),
        new Entry(1021, "Alice", "ofl/alice/Alice-Regular.ttf", false),
        new Entry(1022, "Alien Block", "ofl/alienblock/AlienBlock-Regular.ttf", false),
        new Entry(1023, "Alike Angular", "ofl/alikeangular/AlikeAngular-Regular.ttf", false),
        new Entry(1024, "Alkalami", "ofl/alkalami/Alkalami-Regular.ttf", false),
        new Entry(1025, "Alkatra", "ofl/alkatra/Alkatra[wght].ttf", false),
        new Entry(1026, "Allan", "ofl/allan/Allan-Regular.ttf", false),
        new Entry(1027, "Allison", "ofl/allison/Allison-Regular.ttf", false),
        new Entry(1028, "Allkin", "ofl/allkin/Allkin-Regular.ttf", false),
        new Entry(1029, "Allura", "ofl/allura/Allura-Regular.ttf", false),
        new Entry(1030, "Almarai", "ofl/almarai/Almarai-Regular.ttf", false),
        new Entry(1031, "Almendra Display", "ofl/almendradisplay/AlmendraDisplay-Regular.ttf", false),
        new Entry(1032, "Alumni Sans", "ofl/alumnisans/AlumniSans[wght].ttf", false),
        new Entry(1033, "Alumni Sans Collegiate One", "ofl/alumnisanscollegiateone/AlumniSansCollegiateOne-Regular.ttf", false),
        new Entry(1034, "Alumni Sans Collegiate One SC", "ofl/alumnisanscollegiateonesc/AlumniSansCollegiateOneSC-Regular.ttf", false),
        new Entry(1035, "Alumni Sans Pinstripe", "ofl/alumnisanspinstripe/AlumniSansPinstripe-Regular.ttf", false),
        new Entry(1036, "Alumni Sans SC", "ofl/alumnisanssc/AlumniSansSC[wght].ttf", false),
        new Entry(1037, "Alyamama", "ofl/alyamama/Alyamama[wght].ttf", false),
        new Entry(1038, "Amarante", "ofl/amarante/Amarante-Regular.ttf", false),
        new Entry(1039, "Amaranth", "ofl/amaranth/Amaranth-Regular.ttf", false),
        new Entry(1040, "Amatic SC", "ofl/amaticsc/AmaticSC-Regular.ttf", false),
        new Entry(1041, "Anaheim", "ofl/anaheim/Anaheim[wght].ttf", false),
        new Entry(1042, "Ancizar Sans", "ofl/ancizarsans/AncizarSans[wght].ttf", false),
        new Entry(1043, "Ancizar Serif", "ofl/ancizarserif/AncizarSerif[wght].ttf", false),
        new Entry(1044, "Andika", "ofl/andika/Andika-Regular.ttf", false),
        new Entry(1045, "Anek Bangla", "ofl/anekbangla/AnekBangla[wdth,wght].ttf", false),
        new Entry(1046, "Angkor", "ofl/angkor/Angkor-Regular.ttf", false),
        new Entry(1047, "Annapurna SIL", "ofl/annapurnasil/AnnapurnaSIL-Regular.ttf", false),
        new Entry(1048, "Anta", "ofl/anta/Anta-Regular.ttf", false),
        new Entry(1049, "Antic", "ofl/antic/Antic-Regular.ttf", false),
        new Entry(1050, "Antic Didone", "ofl/anticdidone/AnticDidone-Regular.ttf", false),
        new Entry(1051, "Antic Slab", "ofl/anticslab/AnticSlab-Regular.ttf", false),
        new Entry(1052, "Anton", "ofl/anton/Anton-Regular.ttf", false),
        new Entry(1053, "Anton SC", "ofl/antonsc/AntonSC-Regular.ttf", false),
        new Entry(1054, "Antonio", "ofl/antonio/Antonio[wght].ttf", false),
        new Entry(1055, "Anybody", "ofl/anybody/Anybody[wdth,wght].ttf", false),
        new Entry(1056, "Aoboshi One", "ofl/aoboshione/AoboshiOne-Regular.ttf", false),
        new Entry(1057, "AR One Sans", "ofl/aronesans/AROneSans[ARRR,wght].ttf", false),
        new Entry(1058, "Arapey", "ofl/arapey/Arapey-Regular.ttf", false),
        new Entry(1059, "Arbutus", "ofl/arbutus/Arbutus-Regular.ttf", false),
        new Entry(1060, "Arbutus Slab", "ofl/arbutusslab/ArbutusSlab-Regular.ttf", false),
        new Entry(1061, "Archivo", "ofl/archivo/Archivo[wdth,wght].ttf", false),
        new Entry(1062, "Archivo Black", "ofl/archivoblack/ArchivoBlack-Regular.ttf", false),
        new Entry(1063, "Archivo Narrow", "ofl/archivonarrow/ArchivoNarrow[wght].ttf", false),
        new Entry(1064, "Are You Serious", "ofl/areyouserious/AreYouSerious-Regular.ttf", false),
        new Entry(1065, "Aref Ruqaa", "ofl/arefruqaa/ArefRuqaa-Regular.ttf", false),
        new Entry(1066, "Aref Ruqaa Ink", "ofl/arefruqaaink/ArefRuqaaInk-Regular.ttf", false),
        new Entry(1067, "Arimo", "ofl/arimo/Arimo[wght].ttf", false),
        new Entry(1068, "Arizonia", "ofl/arizonia/Arizonia-Regular.ttf", false),
        new Entry(1069, "Arsenal", "ofl/arsenal/Arsenal-Regular.ttf", false),
        new Entry(1070, "Arsenal SC", "ofl/arsenalsc/ArsenalSC-Regular.ttf", false),
        new Entry(1071, "Artifika", "ofl/artifika/Artifika-Regular.ttf", false),
        new Entry(1072, "Arya", "ofl/arya/Arya-Regular.ttf", false),
        new Entry(1073, "Asar", "ofl/asar/Asar-Regular.ttf", false),
        new Entry(1074, "Asset", "ofl/asset/Asset-Regular.ttf", false),
        new Entry(1075, "Assistant", "ofl/assistant/Assistant[wght].ttf", false),
        new Entry(1076, "Asul", "ofl/asul/Asul-Regular.ttf", false),
        new Entry(1077, "Athiti", "ofl/athiti/Athiti-Regular.ttf", false),
        new Entry(1078, "Atkinson Hyperlegible", "ofl/atkinsonhyperlegible/AtkinsonHyperlegible-Regular.ttf", false),
        new Entry(1079, "Atkinson Hyperlegible Mono", "ofl/atkinsonhyperlegiblemono/AtkinsonHyperlegibleMono[wght].ttf", false),
        new Entry(1080, "Atma", "ofl/atma/Atma-Regular.ttf", false),
        new Entry(1081, "Atomic Age", "ofl/atomicage/AtomicAge-Regular.ttf", false),
        new Entry(1082, "Autour One", "ofl/autourone/AutourOne-Regular.ttf", false),
        new Entry(1083, "Average", "ofl/average/Average-Regular.ttf", false),
        new Entry(1084, "Averia Gruesa Libre", "ofl/averiagruesalibre/AveriaGruesaLibre-Regular.ttf", false),
        new Entry(1085, "Averia Sans Libre", "ofl/averiasanslibre/AveriaSansLibre-Regular.ttf", false),
        new Entry(1086, "Averia Serif Libre", "ofl/averiaseriflibre/AveriaSerifLibre-Regular.ttf", false),
        new Entry(1087, "Azeret Mono", "ofl/azeretmono/AzeretMono[wght].ttf", false),
        new Entry(1088, "B612 Mono", "ofl/b612mono/B612Mono-Regular.ttf", false),
        new Entry(1089, "Bacasime Antique", "ofl/bacasimeantique/BacasimeAntique-Regular.ttf", false),
        new Entry(1090, "Badeen Display", "ofl/badeendisplay/BadeenDisplay-Regular.ttf", false),
        new Entry(1091, "Bagel Fat One", "ofl/bagelfatone/BagelFatOne-Regular.ttf", false),
        new Entry(1092, "Bai Jamjuree", "ofl/baijamjuree/BaiJamjuree-Regular.ttf", false),
        new Entry(1093, "Bakbak One", "ofl/bakbakone/BakbakOne-Regular.ttf", false),
        new Entry(1094, "Ballet", "ofl/ballet/Ballet[opsz].ttf", false),
        new Entry(1095, "Baloo Bhaijaan2", "ofl/baloobhaijaan2/BalooBhaijaan2[wght].ttf", false),
        new Entry(1096, "Baloo Chettan2", "ofl/baloochettan2/BalooChettan2[wght].ttf", false),
        new Entry(1097, "Baloo Da2", "ofl/balooda2/BalooDa2[wght].ttf", false),
        new Entry(1098, "Baloo Tammudu2", "ofl/balootammudu2/BalooTammudu2[wght].ttf", false),
        new Entry(1099, "Baloo Thambi2", "ofl/baloothambi2/BalooThambi2[wght].ttf", false),
        new Entry(1100, "Baloo2", "ofl/baloo2/Baloo2[wght].ttf", false),
        new Entry(1101, "Bangers", "ofl/bangers/Bangers-Regular.ttf", false),
        new Entry(1102, "Barlow Semi Condensed", "ofl/barlowsemicondensed/BarlowSemiCondensed-Regular.ttf", false),
        new Entry(1103, "Barriecito", "ofl/barriecito/Barriecito-Regular.ttf", false),
        new Entry(1104, "Barrio", "ofl/barrio/Barrio-Regular.ttf", false),
        new Entry(1105, "Basic", "ofl/basic/Basic-Regular.ttf", false),
        new Entry(1106, "Baumans", "ofl/baumans/Baumans-Regular.ttf", false),
        new Entry(1107, "Bayon", "ofl/bayon/Bayon-Regular.ttf", false),
        new Entry(1108, "BBH Bartle", "ofl/bbhbartle/BBHBartle-Regular.ttf", false),
        new Entry(1109, "BBH Bogle", "ofl/bbhbogle/BBHBogle-Regular.ttf", false),
        new Entry(1110, "BBH Hegarty", "ofl/bbhhegarty/BBHHegarty-Regular.ttf", false),
        new Entry(1111, "Be Vietnam Pro", "ofl/bevietnampro/BeVietnamPro-Regular.ttf", false),
        new Entry(1112, "Beau Rivage", "ofl/beaurivage/BeauRivage-Regular.ttf", false),
        new Entry(1113, "Beiruti", "ofl/beiruti/Beiruti[wght].ttf", false),
        new Entry(1114, "Belanosima", "ofl/belanosima/Belanosima-Regular.ttf", false),
        new Entry(1115, "Belgrano", "ofl/belgrano/Belgrano-Regular.ttf", false),
        new Entry(1116, "Bellefair", "ofl/bellefair/Bellefair-Regular.ttf", false),
        new Entry(1117, "Belleza", "ofl/belleza/Belleza-Regular.ttf", false),
        new Entry(1118, "Bellota", "ofl/bellota/Bellota-Regular.ttf", false),
        new Entry(1119, "Bench Nine", "ofl/benchnine/BenchNine-Regular.ttf", false),
        new Entry(1120, "Benne", "ofl/benne/Benne-Regular.ttf", false),
        new Entry(1121, "Bentham", "ofl/bentham/Bentham-Regular.ttf", false),
        new Entry(1122, "Besley", "ofl/besley/Besley[wght].ttf", false),
        new Entry(1123, "Betania Patmos GDL", "ofl/betaniapatmosgdl/BetaniaPatmosGDL-Regular.ttf", false),
        new Entry(1124, "Betania Patmos In", "ofl/betaniapatmosin/BetaniaPatmosIn-Regular.ttf", false),
        new Entry(1125, "Beth Ellen", "ofl/bethellen/BethEllen-Regular.ttf", false),
        new Entry(1126, "Bevan", "ofl/bevan/Bevan-Regular.ttf", false),
        new Entry(1127, "Bhavuka", "ofl/bhavuka/Bhavuka-Regular.ttf", false),
        new Entry(1128, "Big Shoulders", "ofl/bigshoulders/BigShoulders[opsz,wght].ttf", false),
        new Entry(1129, "Big Shoulders Display SC", "ofl/bigshouldersdisplaysc/BigShouldersDisplaySC[wght].ttf", false),
        new Entry(1130, "Big Shoulders Inline Display", "ofl/bigshouldersinlinedisplay/BigShouldersInlineDisplay[wght].ttf", false),
        new Entry(1131, "Big Shoulders Inline Text SC", "ofl/bigshouldersinlinetextsc/BigShouldersInlineTextSC[wght].ttf", false),
        new Entry(1132, "Big Shoulders Stencil", "ofl/bigshouldersstencil/BigShouldersStencil[opsz,wght].ttf", false),
        new Entry(1133, "Big Shoulders Stencil Display", "ofl/bigshouldersstencildisplay/BigShouldersStencilDisplay[wght].ttf", false),
        new Entry(1134, "Big Shoulders Stencil Display SC", "ofl/bigshouldersstencildisplaysc/BigShouldersStencilDisplaySC[wght].ttf", false),
        new Entry(1135, "Big Shoulders Stencil Text", "ofl/bigshouldersstenciltext/BigShouldersStencilText[wght].ttf", false),
        new Entry(1136, "Big Shoulders Text", "ofl/bigshoulderstext/BigShouldersText[wght].ttf", false),
        new Entry(1137, "Big Shoulders Text SC", "ofl/bigshoulderstextsc/BigShouldersTextSC[wght].ttf", false),
        new Entry(1138, "Bigelow Rules", "ofl/bigelowrules/BigelowRules-Regular.ttf", false),
        new Entry(1139, "Bilbo Swash Caps", "ofl/bilboswashcaps/BilboSwashCaps-Regular.ttf", false),
        new Entry(1140, "Bio Rhyme", "ofl/biorhyme/BioRhyme[wdth,wght].ttf", false),
        new Entry(1141, "Birthstone", "ofl/birthstone/Birthstone-Regular.ttf", false),
        new Entry(1142, "Birthstone Bounce", "ofl/birthstonebounce/BirthstoneBounce-Regular.ttf", false),
        new Entry(1143, "Biryani", "ofl/biryani/Biryani-Regular.ttf", false),
        new Entry(1144, "Bitcount", "ofl/bitcount/Bitcount[CRSV,ELSH,ELXP,slnt,wght].ttf", false),
        new Entry(1145, "Bitcount Grid Double Ink", "ofl/bitcountgriddoubleink/BitcountGridDoubleInk[CRSV,ELSH,ELXP,SZP1,SZP2,XPN1,XPN2,YPN1,YPN2,slnt,wght].ttf", false),
        new Entry(1146, "Bitcount Prop Double", "ofl/bitcountpropdouble/BitcountPropDouble[CRSV,ELSH,ELXP,slnt,wght].ttf", false),
        new Entry(1147, "Bitcount Prop Single", "ofl/bitcountpropsingle/BitcountPropSingle[CRSV,ELSH,ELXP,slnt,wght].ttf", false),
        new Entry(1148, "Bitcount Prop Single Ink", "ofl/bitcountpropsingleink/BitcountPropSingleInk[CRSV,ELSH,ELXP,SZP1,SZP2,XPN1,XPN2,YPN1,YPN2,slnt,wght].ttf", false),
        new Entry(1149, "Bitcount Single", "ofl/bitcountsingle/BitcountSingle[CRSV,ELSH,ELXP,slnt,wght].ttf", false),
        new Entry(1150, "Bitcount Single Ink", "ofl/bitcountsingleink/BitcountSingleInk[CRSV,ELSH,ELXP,SZP1,SZP2,XPN1,XPN2,YPN1,YPN2,slnt,wght].ttf", false),
        new Entry(1151, "Bitter", "ofl/bitter/Bitter[wght].ttf", false),
        new Entry(1152, "BJ Cree", "ofl/bjcree/BJCree-Regular.ttf", false),
        new Entry(1153, "Black Ops One", "ofl/blackopsone/BlackOpsOne-Regular.ttf", false),
        new Entry(1154, "Blaka Ink", "ofl/blakaink/BlakaInk-Regular.ttf", false),
        new Entry(1155, "Blinker", "ofl/blinker/Blinker-Regular.ttf", false),
        new Entry(1156, "Bodoni Moda", "ofl/bodonimoda/BodoniModa[opsz,wght].ttf", false),
        new Entry(1157, "Bodoni Moda SC", "ofl/bodonimodasc/BodoniModaSC[opsz,wght].ttf", false),
        new Entry(1158, "Bokor", "ofl/bokor/Bokor-Regular.ttf", false),
        new Entry(1159, "Boldonse", "ofl/boldonse/Boldonse-Regular.ttf", false),
        new Entry(1160, "Borel", "ofl/borel/Borel-Regular.ttf", false),
        new Entry(1161, "Bowlby One", "ofl/bowlbyone/BowlbyOne-Regular.ttf", false),
        new Entry(1162, "Bowlby One SC", "ofl/bowlbyonesc/BowlbyOneSC-Regular.ttf", false),
        new Entry(1163, "Braah One", "ofl/braahone/BraahOne-Regular.ttf", false),
        new Entry(1164, "Bruno Ace SC", "ofl/brunoacesc/BrunoAceSC-Regular.ttf", false),
        new Entry(1165, "Bubbler One", "ofl/bubblerone/BubblerOne-Regular.ttf", false),
        new Entry(1166, "Buenard", "ofl/buenard/Buenard[wght].ttf", false),
        new Entry(1167, "Bungee", "ofl/bungee/Bungee-Regular.ttf", false),
        new Entry(1168, "Bungee Color", "ofl/bungeecolor/BungeeColor-Regular.ttf", false),
        new Entry(1169, "Bungee Inline", "ofl/bungeeinline/BungeeInline-Regular.ttf", false),
        new Entry(1170, "Bungee Outline", "ofl/bungeeoutline/BungeeOutline-Regular.ttf", false),
        new Entry(1171, "Bungee Shade", "ofl/bungeeshade/BungeeShade-Regular.ttf", false),
        new Entry(1172, "Bungee Tint", "ofl/bungeetint/BungeeTint-Regular.ttf", false),
        new Entry(1173, "Butterfly Kids", "ofl/butterflykids/ButterflyKids-Regular.ttf", false),
        new Entry(1174, "Bytesized", "ofl/bytesized/Bytesized-Regular.ttf", false),
        new Entry(1175, "Cabin", "ofl/cabin/Cabin[wdth,wght].ttf", false),
        new Entry(1176, "Cabin Condensed", "ofl/cabincondensed/CabinCondensed-Regular.ttf", false),
        new Entry(1177, "Cabin Sketch", "ofl/cabinsketch/CabinSketch-Regular.ttf", false),
        new Entry(1178, "Cagliostro", "ofl/cagliostro/Cagliostro-Regular.ttf", false),
        new Entry(1179, "Cairo Play", "ofl/cairoplay/CairoPlay[slnt,wght].ttf", false),
        new Entry(1180, "Caladea", "ofl/caladea/Caladea-Regular.ttf", false),
        new Entry(1181, "Calistoga", "ofl/calistoga/Calistoga-Regular.ttf", false),
        new Entry(1182, "Cambay", "ofl/cambay/Cambay-Regular.ttf", false),
        new Entry(1183, "Cantata One", "ofl/cantataone/CantataOne-Regular.ttf", false),
        new Entry(1184, "Cantora One", "ofl/cantoraone/CantoraOne-Regular.ttf", false),
        new Entry(1185, "Caprasimo", "ofl/caprasimo/Caprasimo-Regular.ttf", false),
        new Entry(1186, "Capriola", "ofl/capriola/Capriola[wght].ttf", false),
        new Entry(1187, "Carattere", "ofl/carattere/Carattere-Regular.ttf", false),
        new Entry(1188, "Cardo", "ofl/cardo/Cardo-Regular.ttf", false),
        new Entry(1189, "Carlito", "ofl/carlito/Carlito-Regular.ttf", false),
        new Entry(1190, "Carrois Gothic", "ofl/carroisgothic/CarroisGothic-Regular.ttf", false),
        new Entry(1191, "Carrois Gothic SC", "ofl/carroisgothicsc/CarroisGothicSC-Regular.ttf", false),
        new Entry(1192, "Carter One", "ofl/carterone/CarterOne.ttf", false),
        new Entry(1193, "Cascadia Code", "ofl/cascadiacode/CascadiaCode[wght].ttf", false),
        new Entry(1194, "Castoro", "ofl/castoro/Castoro[wght].ttf", false),
        new Entry(1195, "Castoro Titling", "ofl/castorotitling/CastoroTitling-Regular.ttf", false),
        new Entry(1196, "Caveat", "ofl/caveat/Caveat[wght].ttf", false),
        new Entry(1197, "Caveat Brush", "ofl/caveatbrush/CaveatBrush-Regular.ttf", false),
        new Entry(1198, "Cedarville-Cursive", "ofl/cedarvillecursive/Cedarville-Cursive.ttf", false),
        new Entry(1199, "Ceviche One", "ofl/cevicheone/CevicheOne-Regular.ttf", false),
        new Entry(1200, "Changa", "ofl/changa/Changa[wght].ttf", false),
        new Entry(1201, "Charis SIL", "ofl/charissil/CharisSIL-Regular.ttf", false),
        new Entry(1202, "Chau Philomene One", "ofl/chauphilomeneone/ChauPhilomeneOne-Regular.ttf", false),
        new Entry(1203, "Chelsea Market", "ofl/chelseamarket/ChelseaMarket-Regular.ttf", false),
        new Entry(1204, "Chenla", "ofl/chenla/Chenla.ttf", false),
        new Entry(1205, "Cherish", "ofl/cherish/Cherish-Regular.ttf", false),
        new Entry(1206, "Cherry Bomb One", "ofl/cherrybombone/CherryBombOne-Regular.ttf", false),
        new Entry(1207, "Cherry Swash", "ofl/cherryswash/CherrySwash-Regular.ttf", false),
        new Entry(1208, "Chicle", "ofl/chicle/Chicle-Regular.ttf", false),
        new Entry(1209, "Chilanka", "ofl/chilanka/Chilanka-Regular.ttf", false),
        new Entry(1210, "Chivo", "ofl/chivo/Chivo[wght].ttf", false),
        new Entry(1211, "Chokokutai", "ofl/chokokutai/Chokokutai-Regular.ttf", false),
        new Entry(1212, "Cinzel Decorative", "ofl/cinzeldecorative/CinzelDecorative-Regular.ttf", false),
        new Entry(1213, "Clarity City", "ofl/claritycity/ClarityCity[wght].ttf", false),
        new Entry(1214, "Clicker Script", "ofl/clickerscript/ClickerScript-Regular.ttf", false),
        new Entry(1215, "Climate Crisis", "ofl/climatecrisis/ClimateCrisis[YEAR].ttf", false),
        new Entry(1216, "Coda", "ofl/coda/Coda-Regular.ttf", false),
        new Entry(1217, "Codystar", "ofl/codystar/Codystar-Regular.ttf", false),
        new Entry(1218, "Coiny", "ofl/coiny/Coiny-Regular.ttf", false),
        new Entry(1219, "Combo", "ofl/combo/Combo-Regular.ttf", false),
        new Entry(1220, "Comforter", "ofl/comforter/Comforter-Regular.ttf", false),
        new Entry(1221, "Comforter Brush", "ofl/comforterbrush/ComforterBrush-Regular.ttf", false),
        new Entry(1222, "Comic Relief", "ofl/comicrelief/ComicRelief-Regular.ttf", false),
        new Entry(1223, "Comme", "ofl/comme/Comme[wght].ttf", false),
        new Entry(1224, "Commissioner", "ofl/commissioner/Commissioner[FLAR,VOLM,slnt,wght].ttf", false),
        new Entry(1225, "Content", "ofl/content/Content-Regular.ttf", false),
        new Entry(1226, "Contrail One", "ofl/contrailone/ContrailOne-Regular.ttf", false),
        new Entry(1227, "Cookie", "ofl/cookie/Cookie-Regular.ttf", false),
        new Entry(1228, "Copse", "ofl/copse/Copse-Regular.ttf", false),
        new Entry(1229, "Coral Pixels", "ofl/coralpixels/CoralPixels-Regular.ttf", false),
        new Entry(1230, "Corinthia", "ofl/corinthia/Corinthia-Regular.ttf", false),
        new Entry(1231, "Cormorant", "ofl/cormorant/Cormorant[wght].ttf", false),
        new Entry(1232, "Cormorant Garamond", "ofl/cormorantgaramond/CormorantGaramond[wght].ttf", false),
        new Entry(1233, "Cormorant Infant", "ofl/cormorantinfant/CormorantInfant[wght].ttf", false),
        new Entry(1234, "Cormorant SC", "ofl/cormorantsc/CormorantSC-Regular.ttf", false),
        new Entry(1235, "Cormorant Upright", "ofl/cormorantupright/CormorantUpright-Regular.ttf", false),
        new Entry(1236, "Cossette Texte", "ofl/cossettetexte/CossetteTexte-Regular.ttf", false),
        new Entry(1237, "Courgette", "ofl/courgette/Courgette-Regular.ttf", false),
        new Entry(1238, "Covered By Your Grace", "ofl/coveredbyyourgrace/CoveredByYourGrace.ttf", false),
        new Entry(1239, "Creepster", "ofl/creepster/Creepster-Regular.ttf", false),
        new Entry(1240, "Crete Round", "ofl/creteround/CreteRound-Regular.ttf", false),
        new Entry(1241, "Crimson Text", "ofl/crimsontext/CrimsonText-Regular.ttf", false),
        new Entry(1242, "Croissant One", "ofl/croissantone/CroissantOne-Regular.ttf", false),
        new Entry(1243, "Cuprum", "ofl/cuprum/Cuprum[wght].ttf", false),
        new Entry(1244, "Cute Font", "ofl/cutefont/CuteFont-Regular.ttf", false),
        new Entry(1245, "Cutive", "ofl/cutive/Cutive-Regular.ttf", false),
        new Entry(1246, "Cutive Mono", "ofl/cutivemono/CutiveMono-Regular.ttf", false),
        new Entry(1247, "Damion", "ofl/damion/Damion-Regular.ttf", false),
        new Entry(1248, "Danfo", "ofl/danfo/Danfo[ELSH].ttf", false),
        new Entry(1249, "Datatype", "ofl/datatype/Datatype[wdth,wght].ttf", false),
        new Entry(1250, "Decovar Alpha", "ofl/decovaralpha/DecovarAlpha-VF.ttf", false),
        new Entry(1251, "Dekko", "ofl/dekko/Dekko-Regular.ttf", false),
        new Entry(1252, "Dela Gothic One", "ofl/delagothicone/DelaGothicOne-Regular.ttf", false),
        new Entry(1253, "Delicious Handrawn", "ofl/delicioushandrawn/DeliciousHandrawn-Regular.ttf", false),
        new Entry(1254, "Delius", "ofl/delius/Delius-Regular.ttf", false),
        new Entry(1255, "Delius Unicase", "ofl/deliusunicase/DeliusUnicase-Regular.ttf", false),
        new Entry(1256, "Della Respira", "ofl/dellarespira/DellaRespira-Regular.ttf", false),
        new Entry(1257, "Denk One", "ofl/denkone/DenkOne-Regular.ttf", false),
        new Entry(1258, "Devonshire", "ofl/devonshire/Devonshire-Regular.ttf", false),
        new Entry(1259, "Dhurjati", "ofl/dhurjati/Dhurjati-Regular.ttf", false),
        new Entry(1260, "Dhyana", "ofl/dhyana/Dhyana-Regular.ttf", false),
        new Entry(1261, "Didact Gothic", "ofl/didactgothic/DidactGothic-Regular.ttf", false),
        new Entry(1262, "Digital Numbers", "ofl/digitalnumbers/DigitalNumbers-Regular.ttf", false),
        new Entry(1263, "Diplomata", "ofl/diplomata/Diplomata-Regular.ttf", false),
        new Entry(1264, "Diplomata SC", "ofl/diplomatasc/DiplomataSC-Regular.ttf", false),
        new Entry(1265, "DM Mono", "ofl/dmmono/DMMono-Regular.ttf", false),
        new Entry(1266, "DM Sans", "ofl/dmsans/DMSans[opsz,wght].ttf", false),
        new Entry(1267, "Do Hyeon", "ofl/dohyeon/DoHyeon-Regular.ttf", false),
        new Entry(1268, "Domine", "ofl/domine/Domine[wght].ttf", false),
        new Entry(1269, "Donegal One", "ofl/donegalone/DonegalOne-Regular.ttf", false),
        new Entry(1270, "Dongle", "ofl/dongle/Dongle-Regular.ttf", false),
        new Entry(1271, "Doppio One", "ofl/doppioone/DoppioOne-Regular.ttf", false),
        new Entry(1272, "Dr Sugiyama", "ofl/drsugiyama/DrSugiyama-Regular.ttf", false),
        new Entry(1273, "Duru Sans", "ofl/durusans/DuruSans-Regular.ttf", false),
        new Entry(1274, "Dynalight", "ofl/dynalight/Dynalight-Regular.ttf", false),
        new Entry(1275, "East Sea Dokdo", "ofl/eastseadokdo/EastSeaDokdo-Regular.ttf", false),
        new Entry(1276, "Eater", "ofl/eater/Eater-Regular.ttf", false),
        new Entry(1277, "EB Garamond", "ofl/ebgaramond/EBGaramond[wght].ttf", false),
        new Entry(1278, "Eczar", "ofl/eczar/Eczar[wght].ttf", false),
        new Entry(1279, "Edu AUVICWANT Arrows", "ofl/eduauvicwantarrows/EduAUVICWANTArrows[wght].ttf", false),
        new Entry(1280, "Edu AUVICWANT Dots", "ofl/eduauvicwantdots/EduAUVICWANTDots[wght].ttf", false),
        new Entry(1281, "Edu NSWACT Foundation", "ofl/edunswactfoundation/EduNSWACTFoundation[wght].ttf", false),
        new Entry(1282, "Edu SA Beginner", "ofl/edusabeginner/EduSABeginner[wght].ttf", false),
        new Entry(1283, "Edu TAS Beginner", "ofl/edutasbeginner/EduTASBeginner[wght].ttf", false),
        new Entry(1284, "Ek Mukta", "ofl/ekmukta/EkMukta-Regular.ttf", false),
        new Entry(1285, "El Messiri", "ofl/elmessiri/ElMessiri[wght].ttf", false),
        new Entry(1286, "Elms Sans", "ofl/elmssans/ElmsSans[wght].ttf", false),
        new Entry(1287, "Elsie", "ofl/elsie/Elsie-Regular.ttf", false),
        new Entry(1288, "Elsie Swash Caps", "ofl/elsieswashcaps/ElsieSwashCaps-Regular.ttf", false),
        new Entry(1289, "Emilys Candy", "ofl/emilyscandy/EmilysCandy-Regular.ttf", false),
        new Entry(1290, "Encode Sans", "ofl/encodesans/EncodeSans[wdth,wght].ttf", false),
        new Entry(1291, "Encode Sans SC", "ofl/encodesanssc/EncodeSansSC[wdth,wght].ttf", false),
        new Entry(1292, "Encode Sans Semi Condensed", "ofl/encodesanssemicondensed/EncodeSansSemiCondensed-Regular.ttf", false),
        new Entry(1293, "Encode Sans Semi Expanded", "ofl/encodesanssemiexpanded/EncodeSansSemiExpanded-Regular.ttf", false),
        new Entry(1294, "Engagement", "ofl/engagement/Engagement-Regular.ttf", false),
        new Entry(1295, "Englebert", "ofl/englebert/Englebert-Regular.ttf", false),
        new Entry(1296, "Ephesis", "ofl/ephesis/Ephesis-Regular.ttf", false),
        new Entry(1297, "Epilogue", "ofl/epilogue/Epilogue[wght].ttf", false),
        new Entry(1298, "Epunda Sans", "ofl/epundasans/EpundaSans[wght].ttf", false),
        new Entry(1299, "Epunda Slab", "ofl/epundaslab/EpundaSlab[wght].ttf", false),
        new Entry(1300, "Estonia", "ofl/estonia/Estonia-Regular.ttf", false),
        new Entry(1301, "Ewert", "ofl/ewert/Ewert-Regular.ttf", false),
        new Entry(1302, "Exile", "ofl/exile/Exile-Regular.ttf", false),
        new Entry(1303, "Expletus Sans", "ofl/expletussans/ExpletusSans[wght].ttf", false),
        new Entry(1304, "Fahkwang", "ofl/fahkwang/Fahkwang-Regular.ttf", false),
        new Entry(1305, "Familjen Grotesk", "ofl/familjengrotesk/FamiljenGrotesk[wght].ttf", false),
        new Entry(1306, "Farro", "ofl/farro/Farro-Regular.ttf", false),
        new Entry(1307, "Fascinate Inline", "ofl/fascinateinline/FascinateInline-Regular.ttf", false),
        new Entry(1308, "Fasthand", "ofl/fasthand/Fasthand-Regular.ttf", false),
        new Entry(1309, "Fauna One", "ofl/faunaone/FaunaOne-Regular.ttf", false),
        new Entry(1310, "Federant", "ofl/federant/Federant-Regular.ttf", false),
        new Entry(1311, "Finlandica", "ofl/finlandica/Finlandica[wght].ttf", false),
        new Entry(1312, "Finlandica Text", "ofl/finlandicatext/FinlandicaText[wght].ttf", false),
        new Entry(1313, "Fira Code", "ofl/firacode/FiraCode[wght].ttf", false),
        new Entry(1314, "Fira Mono", "ofl/firamono/FiraMono-Regular.ttf", false),
        new Entry(1315, "Fira Sans Extra Condensed", "ofl/firasansextracondensed/FiraSansExtraCondensed-Regular.ttf", false),
        new Entry(1316, "Flavors", "ofl/flavors/Flavors-Regular.ttf", false),
        new Entry(1317, "Fleur De Leah", "ofl/fleurdeleah/FleurDeLeah-Regular.ttf", false),
        new Entry(1318, "Flow Circular", "ofl/flowcircular/FlowCircular-Regular.ttf", false),
        new Entry(1319, "Foldit", "ofl/foldit/Foldit[wght].ttf", false),
        new Entry(1320, "Forum", "ofl/forum/Forum-Regular.ttf", true),
        new Entry(1321, "Fragment Mono", "ofl/fragmentmono/FragmentMono-Regular.ttf", true),
        new Entry(1322, "Frank Ruhl Libre", "ofl/frankruhllibre/FrankRuhlLibre[wght].ttf", true),
        new Entry(1323, "Frederickathe Great", "ofl/frederickathegreat/FrederickatheGreat-Regular.ttf", true),
        new Entry(1324, "Fredoka", "ofl/fredoka/Fredoka[wdth,wght].ttf", true),
        new Entry(1325, "Freeman", "ofl/freeman/Freeman-Regular.ttf", true),
        new Entry(1326, "Fresca", "ofl/fresca/Fresca-Regular.ttf", true),
        new Entry(1327, "Fruktur", "ofl/fruktur/Fruktur-Regular.ttf", true),
        new Entry(1328, "Funnel Display", "ofl/funneldisplay/FunnelDisplay[wght].ttf", true),
        new Entry(1329, "Funnel Sans", "ofl/funnelsans/FunnelSans[wght].ttf", true),
        new Entry(1330, "Fustat", "ofl/fustat/Fustat[wght].ttf", true),
        new Entry(1331, "Gafata", "ofl/gafata/Gafata-Regular.ttf", true),
        new Entry(1332, "Galada", "ofl/galada/Galada-Regular.ttf", true),
        new Entry(1333, "Galdeano", "ofl/galdeano/Galdeano-Regular.ttf", true),
        new Entry(1334, "Galindo", "ofl/galindo/Galindo-Regular.ttf", true),
        new Entry(1335, "Geist", "ofl/geist/Geist[wght].ttf", true),
        new Entry(1336, "Geist Mono", "ofl/geistmono/GeistMono[wght].ttf", true),
        new Entry(1337, "Genos", "ofl/genos/Genos[wght].ttf", true),
        new Entry(1338, "Gentium Book Plus", "ofl/gentiumbookplus/GentiumBookPlus-Regular.ttf", true),
        new Entry(1339, "Gentium Plus", "ofl/gentiumplus/GentiumPlus-Regular.ttf", true),
        new Entry(1340, "Geo", "ofl/geo/Geo-Regular.ttf", true),
        new Entry(1341, "Geomini", "ofl/geomini/Geomini[wght].ttf", true),
        new Entry(1342, "Georama", "ofl/georama/Georama[wdth,wght].ttf", true),
        new Entry(1343, "Geostar", "ofl/geostar/Geostar-Regular.ttf", true),
        new Entry(1344, "Geostar Fill", "ofl/geostarfill/GeostarFill-Regular.ttf", true),
        new Entry(1345, "Germania One", "ofl/germaniaone/GermaniaOne-Regular.ttf", true),
        new Entry(1346, "GFS Neohellenic", "ofl/gfsneohellenic/GFSNeohellenic.ttf", true),
        new Entry(1347, "Gidole", "ofl/gidole/Gidole-Regular.ttf", true),
        new Entry(1348, "Gidugu", "ofl/gidugu/Gidugu-Regular.ttf", true),
        new Entry(1349, "Gilda Display", "ofl/gildadisplay/GildaDisplay-Regular.ttf", true),
        new Entry(1350, "Girassol", "ofl/girassol/Girassol-Regular.ttf", true),
        new Entry(1351, "Give You Glory", "ofl/giveyouglory/GiveYouGlory.ttf", true),
        new Entry(1352, "Glass Antiqua", "ofl/glassantiqua/GlassAntiqua-Regular.ttf", true),
        new Entry(1353, "Glegoo", "ofl/glegoo/Glegoo-Regular.ttf", true),
        new Entry(1354, "Gloock", "ofl/gloock/Gloock-Regular.ttf", true),
        new Entry(1355, "Glory", "ofl/glory/Glory[wght].ttf", true),
        new Entry(1356, "Goblin One", "ofl/goblinone/GoblinOne.ttf", true),
        new Entry(1357, "Gochi Hand", "ofl/gochihand/GochiHand-Regular.ttf", true),
        new Entry(1358, "Goldman", "ofl/goldman/Goldman-Regular.ttf", true),
        new Entry(1359, "Google Sans Code", "ofl/googlesanscode/GoogleSansCode[wght].ttf", true),
        new Entry(1360, "Google Sans Flex", "ofl/googlesansflex/GoogleSansFlex[GRAD,ROND,opsz,slnt,wdth,wght].ttf", true),
        new Entry(1361, "Gorditas", "ofl/gorditas/Gorditas-Regular.ttf", true),
        new Entry(1362, "Gotu", "ofl/gotu/Gotu-Regular.ttf", true),
        new Entry(1363, "Goudy Bookletter1911", "ofl/goudybookletter1911/GoudyBookletter1911.ttf", true),
        new Entry(1364, "Grandstander", "ofl/grandstander/Grandstander[wght].ttf", true),
        new Entry(1365, "Grape Nuts", "ofl/grapenuts/GrapeNuts-Regular.ttf", true),
        new Entry(1366, "Gravitas One", "ofl/gravitasone/GravitasOne.ttf", true),
        new Entry(1367, "Great Vibes", "ofl/greatvibes/GreatVibes-Regular.ttf", true),
        new Entry(1368, "Grenze", "ofl/grenze/Grenze[wght].ttf", true),
        new Entry(1369, "Grey Qo", "ofl/greyqo/GreyQo-Regular.ttf", true),
        new Entry(1370, "Griffy", "ofl/griffy/Griffy-Regular.ttf", true),
        new Entry(1371, "Gruppo", "ofl/gruppo/Gruppo-Regular.ttf", true),
        new Entry(1372, "Gudea", "ofl/gudea/Gudea-Regular.ttf", true),
        new Entry(1373, "Gugi", "ofl/gugi/Gugi-Regular.ttf", true),
        new Entry(1374, "Gulzar", "ofl/gulzar/Gulzar-Regular.ttf", true),
        new Entry(1375, "Gupter", "ofl/gupter/Gupter-Regular.ttf", true),
        new Entry(1376, "Gveret Levin", "ofl/gveretlevin/GveretLevin-Regular.ttf", true),
        new Entry(1377, "Gwendolyn", "ofl/gwendolyn/Gwendolyn-Regular.ttf", true),
        new Entry(1378, "Habibi", "ofl/habibi/Habibi-Regular.ttf", true),
        new Entry(1379, "Hahmlet", "ofl/hahmlet/Hahmlet[wght].ttf", true),
        new Entry(1380, "Hammersmith One", "ofl/hammersmithone/HammersmithOne-Regular.ttf", true),
        new Entry(1381, "Hanalei Fill", "ofl/hanaleifill/HanaleiFill-Regular.ttf", true),
        new Entry(1382, "Handlee", "ofl/handlee/Handlee-Regular.ttf", true),
        new Entry(1383, "Hannari", "ofl/hannari/Hannari-Regular.ttf", true),
        new Entry(1384, "Hanuman", "ofl/hanuman/Hanuman[wght].ttf", true),
        new Entry(1385, "Happy Monkey", "ofl/happymonkey/HappyMonkey-Regular.ttf", true),
        new Entry(1386, "Harmattan", "ofl/harmattan/Harmattan-Regular.ttf", true),
        new Entry(1387, "Hedvig Letters Sans", "ofl/hedvigletterssans/HedvigLettersSans-Regular.ttf", true),
        new Entry(1388, "Hedvig Letters Serif", "ofl/hedviglettersserif/HedvigLettersSerif[opsz].ttf", true),
        new Entry(1389, "Heebo", "ofl/heebo/Heebo[wght].ttf", true),
        new Entry(1390, "Henny Penny", "ofl/hennypenny/HennyPenny-Regular.ttf", true),
        new Entry(1391, "Hepta Slab", "ofl/heptaslab/HeptaSlab[wght].ttf", true),
        new Entry(1392, "Hermeneus One", "ofl/hermeneusone/HermeneusOne-Regular.ttf", true),
        new Entry(1393, "Herr Von Muellerhoff", "ofl/herrvonmuellerhoff/HerrVonMuellerhoff-Regular.ttf", true),
        new Entry(1394, "Hind Colombo", "ofl/hindcolombo/HindColombo-Regular.ttf", true),
        new Entry(1395, "Hind Mysuru", "ofl/hindmysuru/HindMysuru-Regular.ttf", true),
        new Entry(1396, "Hind Siliguri", "ofl/hindsiliguri/HindSiliguri-Regular.ttf", true),
        new Entry(1397, "Hind Vadodara", "ofl/hindvadodara/HindVadodara-Regular.ttf", true),
        new Entry(1398, "Holtwood One SC", "ofl/holtwoodonesc/HoltwoodOneSC-Regular.ttf", true),
        new Entry(1399, "Homenaje", "ofl/homenaje/Homenaje-Regular.ttf", true),
        new Entry(1400, "Hubot Sans", "ofl/hubotsans/HubotSans[wdth,wght].ttf", true),
        new Entry(1401, "Hurricane", "ofl/hurricane/Hurricane-Regular.ttf", true),
        new Entry(1402, "IBM Plex Sans", "ofl/ibmplexsans/IBMPlexSans[wdth,wght].ttf", true),
        new Entry(1403, "IBM Plex Sans Condensed", "ofl/ibmplexsanscondensed/IBMPlexSansCondensed-Regular.ttf", true),
        new Entry(1404, "IBM Plex Sans KR", "ofl/ibmplexsanskr/IBMPlexSansKR-Regular.ttf", true),
        new Entry(1405, "Iceberg", "ofl/iceberg/Iceberg-Regular.ttf", true),
        new Entry(1406, "Idiqlat", "ofl/idiqlat/Idiqlat-Regular.ttf", true),
        new Entry(1407, "IM Fe D Psc28 P", "ofl/imfelldoublepicasc/IMFeDPsc28P.ttf", true),
        new Entry(1408, "IM Fe E Nit28 P", "ofl/imfellenglish/IMFeENit28P.ttf", true),
        new Entry(1409, "IM Fe E Nsc28 P", "ofl/imfellenglishsc/IMFeENsc28P.ttf", true),
        new Entry(1410, "IM Fe F Cit28 P", "ofl/imfellfrenchcanon/IMFeFCit28P.ttf", true),
        new Entry(1411, "IM Fe F Csc28 P", "ofl/imfellfrenchcanonsc/IMFeFCsc28P.ttf", true),
        new Entry(1412, "IM Fe G Pit28 P", "ofl/imfellgreatprimer/IMFeGPit28P.ttf", true),
        new Entry(1413, "IM Fe G Psc28 P", "ofl/imfellgreatprimersc/IMFeGPsc28P.ttf", true),
        new Entry(1414, "IMFELL Double Pica", "ofl/imfelldoublepica/IMFELLDoublePica-Regular.ttf", true),
        new Entry(1415, "Imperial Script", "ofl/imperialscript/ImperialScript-Regular.ttf", true),
        new Entry(1416, "Imprima", "ofl/imprima/Imprima-Regular.ttf", true),
        new Entry(1417, "Inclusive Sans", "ofl/inclusivesans/InclusiveSans[wght].ttf", true),
        new Entry(1418, "Inika", "ofl/inika/Inika-Regular.ttf", true),
        new Entry(1419, "Inknut Antiqua", "ofl/inknutantiqua/InknutAntiqua-Regular.ttf", true),
        new Entry(1420, "Inria Serif", "ofl/inriaserif/InriaSerif-Regular.ttf", true),
        new Entry(1421, "Instrument Sans", "ofl/instrumentsans/InstrumentSans[wdth,wght].ttf", true),
        new Entry(1422, "Instrument Serif", "ofl/instrumentserif/InstrumentSerif-Regular.ttf", true),
        new Entry(1423, "Inter", "ofl/inter/Inter[opsz,wght].ttf", true),
        new Entry(1424, "Iosevka Charon", "ofl/iosevkacharon/IosevkaCharon-Regular.ttf", true),
        new Entry(1425, "Island Moments", "ofl/islandmoments/IslandMoments-Regular.ttf", true),
        new Entry(1426, "Isometra", "ofl/isometra/Isometra-Regular.ttf", true),
        new Entry(1427, "Istok Web", "ofl/istokweb/IstokWeb-Regular.ttf", true),
        new Entry(1428, "Itim", "ofl/itim/Itim-Regular.ttf", true),
        new Entry(1429, "Jacquard12", "ofl/jacquard12/Jacquard12-Regular.ttf", true),
        new Entry(1430, "Jacquard12 Charted", "ofl/jacquard12charted/Jacquard12Charted-Regular.ttf", true),
        new Entry(1431, "Jacquard24", "ofl/jacquard24/Jacquard24-Regular.ttf", true),
        new Entry(1432, "Jacquarda Bastarda9 Charted", "ofl/jacquardabastarda9charted/JacquardaBastarda9Charted-Regular.ttf", true),
        new Entry(1433, "Jacques Francois Shadow", "ofl/jacquesfrancoisshadow/JacquesFrancoisShadow-Regular.ttf", true),
        new Entry(1434, "Jaini", "ofl/jaini/Jaini-Regular.ttf", true),
        new Entry(1435, "Jaldi", "ofl/jaldi/Jaldi-Regular.ttf", true),
        new Entry(1436, "Jaro", "ofl/jaro/Jaro[opsz].ttf", true),
        new Entry(1437, "Jeju Gothic", "ofl/jejugothic/JejuGothic-Regular.ttf", true),
        new Entry(1438, "Jersey10", "ofl/jersey10/Jersey10-Regular.ttf", true),
        new Entry(1439, "Jersey15 Charted", "ofl/jersey15charted/Jersey15Charted-Regular.ttf", true),
        new Entry(1440, "Jersey20", "ofl/jersey20/Jersey20-Regular.ttf", true),
        new Entry(1441, "Jersey20 Charted", "ofl/jersey20charted/Jersey20Charted-Regular.ttf", true),
        new Entry(1442, "Jet Brains Mono", "ofl/jetbrainsmono/JetBrainsMono[wght].ttf", true),
        new Entry(1443, "Jim Nightshade", "ofl/jimnightshade/JimNightshade-Regular.ttf", true),
        new Entry(1444, "Joan", "ofl/joan/Joan-Regular.ttf", true),
        new Entry(1445, "Josefin Sans", "ofl/josefinsans/JosefinSans[wght].ttf", true),
        new Entry(1446, "Joti One", "ofl/jotione/JotiOne-Regular.ttf", true),
        new Entry(1447, "Jua", "ofl/jua/Jua-Regular.ttf", true),
        new Entry(1448, "Judson", "ofl/judson/Judson-Regular.ttf", true),
        new Entry(1449, "Julee", "ofl/julee/Julee-Regular.ttf", true),
        new Entry(1450, "Julius Sans One", "ofl/juliussansone/JuliusSansOne-Regular.ttf", true),
        new Entry(1451, "Junge", "ofl/junge/Junge-Regular.ttf", true),
        new Entry(1452, "Jura", "ofl/jura/Jura[wght].ttf", true),
        new Entry(1453, "K2 D", "ofl/k2d/K2D-Regular.ttf", true),
        new Entry(1454, "Kablammo", "ofl/kablammo/Kablammo[MORF].ttf", true),
        new Entry(1455, "Kaisei Decol", "ofl/kaiseidecol/KaiseiDecol-Medium.ttf", true),
        new Entry(1456, "Kaisei Opti", "ofl/kaiseiopti/KaiseiOpti-Medium.ttf", true),
        new Entry(1457, "Kaisei Tokumin", "ofl/kaiseitokumin/KaiseiTokumin-Medium.ttf", true),
        new Entry(1458, "Kalnia Glaze", "ofl/kalniaglaze/KalniaGlaze[wdth,wght].ttf", true),
        new Entry(1459, "Kameron", "ofl/kameron/Kameron[wght].ttf", true),
        new Entry(1460, "Kanchenjunga", "ofl/kanchenjunga/Kanchenjunga-Regular.ttf", true),
        new Entry(1461, "Kanit", "ofl/kanit/Kanit-Regular.ttf", true),
        new Entry(1462, "Karla", "ofl/karla/Karla[wght].ttf", true),
        new Entry(1463, "Karma", "ofl/karma/Karma-Regular.ttf", true),
        new Entry(1464, "Kaushan Script", "ofl/kaushanscript/KaushanScript-Regular.ttf", true),
        new Entry(1465, "Kavoon", "ofl/kavoon/Kavoon-Regular.ttf", true),
        new Entry(1466, "Kay Pho Du", "ofl/kayphodu/KayPhoDu-Regular.ttf", true),
        new Entry(1467, "Kdam Thmor Pro", "ofl/kdamthmorpro/KdamThmorPro-Regular.ttf", true),
        new Entry(1468, "Khand", "ofl/khand/Khand-Regular.ttf", true),
        new Entry(1469, "Kings", "ofl/kings/Kings-Regular.ttf", true),
        new Entry(1470, "Kite One", "ofl/kiteone/KiteOne-Regular.ttf", true),
        new Entry(1471, "Ko Ho", "ofl/koho/KoHo-Regular.ttf", true),
        new Entry(1472, "Kode Mono", "ofl/kodemono/KodeMono[wght].ttf", true),
        new Entry(1473, "Koh Santepheap", "ofl/kohsantepheap/KohSantepheap-Regular.ttf", true),
        new Entry(1474, "Kokoro", "ofl/kokoro/Kokoro-Regular.ttf", true),
        new Entry(1475, "Kotta One", "ofl/kottaone/KottaOne-Regular.ttf", true),
        new Entry(1476, "Koulen", "ofl/koulen/Koulen-Regular.ttf", true),
        new Entry(1477, "Kreon", "ofl/kreon/Kreon[wght].ttf", true),
        new Entry(1478, "Kristi", "ofl/kristi/Kristi-Regular.ttf", true),
        new Entry(1479, "Krona One", "ofl/kronaone/KronaOne-Regular.ttf", true),
        new Entry(1480, "Kufam", "ofl/kufam/Kufam[wght].ttf", true),
        new Entry(1481, "Kumar One", "ofl/kumarone/KumarOne-Regular.ttf", true),
        new Entry(1482, "Kumar One Outline", "ofl/kumaroneoutline/KumarOneOutline-Regular.ttf", true),
        new Entry(1483, "Kurale", "ofl/kurale/Kurale-Regular.ttf", true),
        new Entry(1484, "Lacquer", "ofl/lacquer/Lacquer-Regular.ttf", true),
        new Entry(1485, "Lancelot", "ofl/lancelot/Lancelot-Regular.ttf", true),
        new Entry(1486, "Langar", "ofl/langar/Langar-Regular.ttf", true),
        new Entry(1487, "Lato", "ofl/lato/Lato-Regular.ttf", true),
        new Entry(1488, "Lavishly Yours", "ofl/lavishlyyours/LavishlyYours-Regular.ttf", true),
        new Entry(1489, "Leckerli One", "ofl/leckerlione/LeckerliOne-Regular.ttf", true),
        new Entry(1490, "Ledger", "ofl/ledger/Ledger-Regular.ttf", true),
        new Entry(1491, "Lekton", "ofl/lekton/Lekton-Regular.ttf", true),
        new Entry(1492, "Lemonada", "ofl/lemonada/Lemonada[wght].ttf", true),
        new Entry(1493, "Lemonada VF Beta", "ofl/lemonadavfbeta/LemonadaVFBeta.ttf", true),
        new Entry(1494, "Lexend", "ofl/lexend/Lexend[wght].ttf", true),
        new Entry(1495, "Lexend Giga", "ofl/lexendgiga/LexendGiga[wght].ttf", true),
        new Entry(1496, "Lexend Mega", "ofl/lexendmega/LexendMega[wght].ttf", true),
        new Entry(1497, "Libertinus Keyboard", "ofl/libertinuskeyboard/LibertinusKeyboard-Regular.ttf", true),
        new Entry(1498, "Libertinus Mono", "ofl/libertinusmono/LibertinusMono-Regular.ttf", true),
        new Entry(1499, "Libertinus Serif", "ofl/libertinusserif/LibertinusSerif-Regular.ttf", true),
        new Entry(1500, "Libertinus Serif Display", "ofl/libertinusserifdisplay/LibertinusSerifDisplay-Regular.ttf", true),
        new Entry(1501, "Libre Barcode EAN13 Text", "ofl/librebarcodeean13text/LibreBarcodeEAN13Text-Regular.ttf", true),
        new Entry(1502, "Libre Barcode39", "ofl/librebarcode39/LibreBarcode39-Regular.ttf", true),
        new Entry(1503, "Libre Barcode39 Text", "ofl/librebarcode39text/LibreBarcode39Text-Regular.ttf", true),
        new Entry(1504, "Libre Bodoni", "ofl/librebodoni/LibreBodoni[wght].ttf", true),
        new Entry(1505, "Libre Caslon Display", "ofl/librecaslondisplay/LibreCaslonDisplay-Regular.ttf", true),
        new Entry(1506, "Libre Franklin", "ofl/librefranklin/LibreFranklin[wght].ttf", true),
        new Entry(1507, "Lilita One", "ofl/lilitaone/LilitaOne-Regular.ttf", true),
        new Entry(1508, "Linden Hill", "ofl/lindenhill/LindenHill-Regular.ttf", true),
        new Entry(1509, "Lisu Bosa", "ofl/lisubosa/LisuBosa-Regular.ttf", true),
        new Entry(1510, "Literata", "ofl/literata/Literata[opsz,wght].ttf", true),
        new Entry(1511, "Lobster Two", "ofl/lobstertwo/LobsterTwo-Regular.ttf", true),
        new Entry(1512, "Londrina Sketch", "ofl/londrinasketch/LondrinaSketch-Regular.ttf", true),
        new Entry(1513, "Londrina Solid", "ofl/londrinasolid/LondrinaSolid-Regular.ttf", true),
        new Entry(1514, "Love Light", "ofl/lovelight/LoveLight-Regular.ttf", true),
        new Entry(1515, "Love Ya Like A Sister", "ofl/loveyalikeasister/LoveYaLikeASister.ttf", true),
        new Entry(1516, "Lovedbythe King", "ofl/lovedbytheking/LovedbytheKing.ttf", true),
        new Entry(1517, "Lugrasimo", "ofl/lugrasimo/Lugrasimo-Regular.ttf", true),
        new Entry(1518, "Lusitana", "ofl/lusitana/Lusitana-Regular.ttf", true),
        new Entry(1519, "Luxurious Roman", "ofl/luxuriousroman/LuxuriousRoman-Regular.ttf", true),
        new Entry(1520, "Luxurious Script", "ofl/luxuriousscript/LuxuriousScript-Regular.ttf", true),
        new Entry(1521, "LXGW Marker Gothic", "ofl/lxgwmarkergothic/LXGWMarkerGothic-Regular.ttf", true),
        new Entry(1522, "Macondo Swash Caps", "ofl/macondoswashcaps/MacondoSwashCaps-Regular.ttf", true),
        new Entry(1523, "Madimi One", "ofl/madimione/MadimiOne-Regular.ttf", true),
        new Entry(1524, "Magra", "ofl/magra/Magra-Regular.ttf", true),
        new Entry(1525, "Maitree", "ofl/maitree/Maitree-Regular.ttf", true),
        new Entry(1526, "Major Mono Display", "ofl/majormonodisplay/MajorMonoDisplay-Regular.ttf", true),
        new Entry(1527, "Mako", "ofl/mako/Mako-Regular.ttf", true),
        new Entry(1528, "Mandali", "ofl/mandali/Mandali-Regular.ttf", true),
        new Entry(1529, "Manjari", "ofl/manjari/Manjari-Regular.ttf", true),
        new Entry(1530, "Manrope", "ofl/manrope/Manrope[wght].ttf", true),
        new Entry(1531, "Manuale", "ofl/manuale/Manuale[wght].ttf", true),
        new Entry(1532, "Marcellus", "ofl/marcellus/Marcellus-Regular.ttf", true),
        new Entry(1533, "Marcellus SC", "ofl/marcellussc/MarcellusSC-Regular.ttf", true),
        new Entry(1534, "Marck Script", "ofl/marckscript/MarckScript-Regular.ttf", true),
        new Entry(1535, "Marhey", "ofl/marhey/Marhey[wght].ttf", true),
        new Entry(1536, "Marko One", "ofl/markoone/MarkoOne-Regular.ttf", true),
        new Entry(1537, "Martel", "ofl/martel/Martel-Regular.ttf", true),
        new Entry(1538, "Martian Mono", "ofl/martianmono/MartianMono[wdth,wght].ttf", true),
        new Entry(1539, "Matangi", "ofl/matangi/Matangi[wght].ttf", true),
        new Entry(1540, "Mate SC", "ofl/matesc/MateSC-Regular.ttf", true),
        new Entry(1541, "Matemasie", "ofl/matemasie/Matemasie-Regular.ttf", true),
        new Entry(1542, "Mc Laren", "ofl/mclaren/McLaren-Regular.ttf", true),
        new Entry(1543, "Mea Culpa", "ofl/meaculpa/MeaCulpa-Regular.ttf", true),
        new Entry(1544, "Medieval Sharp", "ofl/medievalsharp/MedievalSharp.ttf", true),
        new Entry(1545, "Megrim", "ofl/megrim/Megrim.ttf", true),
        new Entry(1546, "Merienda", "ofl/merienda/Merienda[wght].ttf", true),
        new Entry(1547, "Merriweather Sans", "ofl/merriweathersans/MerriweatherSans[wght].ttf", true),
        new Entry(1548, "Mervale Script", "ofl/mervalescript/MervaleScript-Regular.ttf", true),
        new Entry(1549, "Metal", "ofl/metal/Metal-Regular.ttf", true),
        new Entry(1550, "Metal Mania", "ofl/metalmania/MetalMania-Regular.ttf", true),
        new Entry(1551, "Michroma", "ofl/michroma/Michroma-Regular.ttf", true),
        new Entry(1552, "Micro5", "ofl/micro5/Micro5-Regular.ttf", true),
        new Entry(1553, "Milonga", "ofl/milonga/Milonga-Regular.ttf", true),
        new Entry(1554, "Miltonian", "ofl/miltonian/Miltonian-Regular.ttf", true),
        new Entry(1555, "Miltonian Tattoo", "ofl/miltoniantattoo/MiltonianTattoo-Regular.ttf", true),
        new Entry(1556, "Mina", "ofl/mina/Mina-Regular.ttf", true),
        new Entry(1557, "Miniver", "ofl/miniver/Miniver-Regular.ttf", true),
        new Entry(1558, "Miranda Sans", "ofl/mirandasans/MirandaSans[wght].ttf", true),
        new Entry(1559, "Miriam Libre", "ofl/miriamlibre/MiriamLibre[wght].ttf", true),
        new Entry(1560, "Mirza", "ofl/mirza/Mirza-Regular.ttf", true),
        new Entry(1561, "Mitr", "ofl/mitr/Mitr-Regular.ttf", true),
        new Entry(1562, "Modak", "ofl/modak/Modak-Regular.ttf", true),
        new Entry(1563, "Modern Antiqua", "ofl/modernantiqua/ModernAntiqua-Regular.ttf", true),
        new Entry(1564, "Moderustic", "ofl/moderustic/Moderustic[wght].ttf", true),
        new Entry(1565, "Mogra", "ofl/mogra/Mogra-Regular.ttf", true),
        new Entry(1566, "Molle", "ofl/molle/Molle-Regular.ttf", true),
        new Entry(1567, "Momo Signature", "ofl/momosignature/MomoSignature-Regular.ttf", true),
        new Entry(1568, "Momo Trust Sans", "ofl/momotrustsans/MomoTrustSans[wght].ttf", true),
        new Entry(1569, "Mona Sans", "ofl/monasans/MonaSans[wdth,wght].ttf", true),
        new Entry(1570, "Monda", "ofl/monda/Monda[wght].ttf", true),
        new Entry(1571, "Monofett", "ofl/monofett/Monofett-Regular.ttf", true),
        new Entry(1572, "Monomaniac One", "ofl/monomaniacone/MonomaniacOne-Regular.ttf", true),
        new Entry(1573, "Montaga", "ofl/montaga/Montaga-Regular.ttf", true),
        new Entry(1574, "Montenegrin Gothic One", "ofl/montenegringothicone/MontenegrinGothicOne-Regular.ttf", true),
        new Entry(1575, "Montserrat Underline", "ofl/montserratunderline/MontserratUnderline[wght].ttf", true),
        new Entry(1576, "Moon Dance", "ofl/moondance/MoonDance-Regular.ttf", true),
        new Entry(1577, "Moul", "ofl/moul/Moul-Regular.ttf", true),
        new Entry(1578, "Moulpali", "ofl/moulpali/Moulpali-Regular.ttf", true),
        new Entry(1579, "Mouse Memoirs", "ofl/mousememoirs/MouseMemoirs-Regular.ttf", true),
        new Entry(1580, "Mozilla Headline", "ofl/mozillaheadline/MozillaHeadline[wdth,wght].ttf", true),
        new Entry(1581, "Mozilla Text", "ofl/mozillatext/MozillaText[wght].ttf", true),
        new Entry(1582, "MPLUS Code Latin", "ofl/mpluscodelatin/MPLUSCodeLatin[wdth,wght].ttf", true),
        new Entry(1583, "MPLUS Rounded1c", "ofl/mplusrounded1c/MPLUSRounded1c-Regular.ttf", true),
        new Entry(1584, "MPLUS1 Code", "ofl/mplus1code/MPLUS1Code[wght].ttf", true),
        new Entry(1585, "MPLUS2", "ofl/mplus2/MPLUS2[wght].ttf", true),
        new Entry(1586, "MPLUSU", "ofl/mplusu/MPLUSU[wght].ttf", true),
        new Entry(1587, "Mr De Haviland", "ofl/mrdehaviland/MrDeHaviland-Regular.ttf", true),
        new Entry(1588, "Mrs Saint Delafield", "ofl/mrssaintdelafield/MrsSaintDelafield-Regular.ttf", true),
        new Entry(1589, "Mrs Sheppards", "ofl/mrssheppards/MrsSheppards-Regular.ttf", true),
        new Entry(1590, "Ms Madi", "ofl/msmadi/MsMadi-Regular.ttf", true),
        new Entry(1591, "Mukta", "ofl/mukta/Mukta-Regular.ttf", true),
        new Entry(1592, "Mukta Vaani", "ofl/muktavaani/MuktaVaani-Regular.ttf", true),
        new Entry(1593, "Mulish", "ofl/mulish/Mulish[wght].ttf", true),
        new Entry(1594, "Murecho", "ofl/murecho/Murecho[wght].ttf", true),
        new Entry(1595, "My Soul", "ofl/mysoul/MySoul-Regular.ttf", true),
        new Entry(1596, "Myanmar Sans Pro", "ofl/myanmarsanspro/MyanmarSansPro-Regular.ttf", true),
        new Entry(1597, "Mynerve", "ofl/mynerve/Mynerve-Regular.ttf", true),
        new Entry(1598, "Nabla", "ofl/nabla/Nabla[EDPT,EHLT].ttf", true),
        new Entry(1599, "Namdhinggo", "ofl/namdhinggo/Namdhinggo-Regular.ttf", true),
        new Entry(1600, "Nanum Brush Script", "ofl/nanumbrushscript/NanumBrushScript-Regular.ttf", true),
        new Entry(1601, "Nanum Myeongjo", "ofl/nanummyeongjo/NanumMyeongjo-Regular.ttf", true),
        new Entry(1602, "Nanum Pen Script", "ofl/nanumpenscript/NanumPenScript-Regular.ttf", true),
        new Entry(1603, "Narnoor", "ofl/narnoor/Narnoor-Regular.ttf", true),
        new Entry(1604, "NATS", "ofl/nats/NATS-Regular.ttf", true),
        new Entry(1605, "Neonderthaw", "ofl/neonderthaw/Neonderthaw-Regular.ttf", true),
        new Entry(1606, "Nerko One", "ofl/nerkoone/NerkoOne-Regular.ttf", true),
        new Entry(1607, "Neucha", "ofl/neucha/Neucha.ttf", true),
        new Entry(1608, "Nevermind", "ofl/nevermind/Nevermind[wght].ttf", true),
        new Entry(1609, "New Rocker", "ofl/newrocker/NewRocker-Regular.ttf", true),
        new Entry(1610, "Newsreader", "ofl/newsreader/Newsreader[opsz,wght].ttf", true),
        new Entry(1611, "Nikukyu", "ofl/nikukyu/Nikukyu-Regular.ttf", true),
        new Entry(1612, "Nixie One", "ofl/nixieone/NixieOne-Regular.ttf", true),
        new Entry(1613, "Nobile", "ofl/nobile/Nobile-Regular.ttf", true),
        new Entry(1614, "Nokora", "ofl/nokora/Nokora[wght].ttf", true),
        new Entry(1615, "Nosifer Caps", "ofl/nosifercaps/NosiferCaps-Regular.ttf", true),
        new Entry(1616, "Notable", "ofl/notable/Notable-Regular.ttf", true),
        new Entry(1617, "Nothing You Could Do", "ofl/nothingyoucoulddo/NothingYouCouldDo.ttf", true),
        new Entry(1618, "Noticia Text", "ofl/noticiatext/NoticiaText-Regular.ttf", true),
        new Entry(1619, "Nova Cut", "ofl/novacut/NovaCut.ttf", true),
        new Entry(1620, "Nova Mono", "ofl/novamono/NovaMono.ttf", true),
        new Entry(1621, "Nova Round", "ofl/novaround/NovaRound.ttf", true),
        new Entry(1622, "Nova Script", "ofl/novascript/NovaScript-Regular.ttf", true),
        new Entry(1623, "NTR", "ofl/ntr/NTR-Regular.ttf", true),
        new Entry(1624, "Numans", "ofl/numans/Numans-Regular.ttf", true),
        new Entry(1625, "Nunito", "ofl/nunito/Nunito[wght].ttf", true),
        new Entry(1626, "Nunito Sans", "ofl/nunitosans/NunitoSans[YTLC,opsz,wdth,wght].ttf", true),
        new Entry(1627, "Nuosu SIL", "ofl/nuosusil/NuosuSIL-Regular.ttf", true),
        new Entry(1628, "Odibee Sans", "ofl/odibeesans/OdibeeSans-Regular.ttf", true),
        new Entry(1629, "Odor Mean Chey", "ofl/odormeanchey/OdorMeanChey-Regular.ttf", true),
        new Entry(1630, "Ojuju", "ofl/ojuju/Ojuju[wght].ttf", true),
        new Entry(1631, "Old Standard", "ofl/oldstandardtt/OldStandard-Regular.ttf", true),
        new Entry(1632, "Oldenburg", "ofl/oldenburg/Oldenburg-Regular.ttf", true),
        new Entry(1633, "Ole", "ofl/ole/Ole-Regular.ttf", true),
        new Entry(1634, "Oleo Script", "ofl/oleoscript/OleoScript-Regular.ttf", true),
        new Entry(1635, "Onest", "ofl/onest/Onest[wght].ttf", true),
        new Entry(1636, "Oooh Baby", "ofl/ooohbaby/OoohBaby-Regular.ttf", true),
        new Entry(1637, "Open Sans", "ofl/opensans/OpenSans[wdth,wght].ttf", true),
        new Entry(1638, "Oranienbaum", "ofl/oranienbaum/Oranienbaum-Regular.ttf", true),
        new Entry(1639, "Orbit", "ofl/orbit/Orbit-Regular.ttf", true),
        new Entry(1640, "Orbitron", "ofl/orbitron/Orbitron[wght].ttf", true),
        new Entry(1641, "Oregano", "ofl/oregano/Oregano-Regular.ttf", true),
        new Entry(1642, "Orelega One", "ofl/orelegaone/OrelegaOne-Regular.ttf", true),
        new Entry(1643, "Orienta", "ofl/orienta/Orienta-Regular.ttf", true),
        new Entry(1644, "Original Surfer", "ofl/originalsurfer/OriginalSurfer-Regular.ttf", true),
        new Entry(1645, "Oswald", "ofl/oswald/Oswald[wght].ttf", true),
        new Entry(1646, "Otomanopee One", "ofl/otomanopeeone/OtomanopeeOne-Regular.ttf", true),
        new Entry(1647, "Overlock", "ofl/overlock/Overlock-Regular.ttf", true),
        new Entry(1648, "Overlock SC", "ofl/overlocksc/OverlockSC-Regular.ttf", true),
        new Entry(1649, "Overpass", "ofl/overpass/Overpass[wght].ttf", true),
        new Entry(1650, "Overpass Mono", "ofl/overpassmono/OverpassMono[wght].ttf", true),
        new Entry(1651, "Overthe Rainbow", "ofl/overtherainbow/OvertheRainbow.ttf", true),
        new Entry(1652, "Ovo", "ofl/ovo/Ovo-Regular.ttf", true),
        new Entry(1653, "Oxanium", "ofl/oxanium/Oxanium[wght].ttf", true),
        new Entry(1654, "Oxygen Mono", "ofl/oxygenmono/OxygenMono-Regular.ttf", true),
        new Entry(1655, "Pacifico", "ofl/pacifico/Pacifico-Regular.ttf", true),
        new Entry(1656, "Palanquin", "ofl/palanquin/Palanquin-Regular.ttf", true),
        new Entry(1657, "Pangolin", "ofl/pangolin/Pangolin-Regular.ttf", true),
        new Entry(1658, "Paprika", "ofl/paprika/Paprika-Regular.ttf", true),
        new Entry(1659, "Parastoo", "ofl/parastoo/Parastoo[wght].ttf", true),
        new Entry(1660, "Parisienne", "ofl/parisienne/Parisienne-Regular.ttf", true),
        new Entry(1661, "Parkinsans", "ofl/parkinsans/Parkinsans[wght].ttf", true),
        new Entry(1662, "Passion One", "ofl/passionone/PassionOne-Regular.ttf", true),
        new Entry(1663, "Passions Conflict", "ofl/passionsconflict/PassionsConflict-Regular.ttf", true),
        new Entry(1664, "Pathway Gothic One", "ofl/pathwaygothicone/PathwayGothicOne-Regular.ttf", true),
        new Entry(1665, "Patrick Hand", "ofl/patrickhand/PatrickHand-Regular.ttf", true),
        new Entry(1666, "Pattaya", "ofl/pattaya/Pattaya-Regular.ttf", true),
        new Entry(1667, "Pavanam", "ofl/pavanam/Pavanam-Regular.ttf", true),
        new Entry(1668, "Paytone One", "ofl/paytoneone/PaytoneOne-Regular.ttf", true),
        new Entry(1669, "Peddana", "ofl/peddana/Peddana-Regular.ttf", true),
        new Entry(1670, "Petemoss", "ofl/petemoss/Petemoss-Regular.ttf", true),
        new Entry(1671, "Petit Formal Script", "ofl/petitformalscript/PetitFormalScript-Regular.ttf", true),
        new Entry(1672, "Petrona", "ofl/petrona/Petrona[wght].ttf", true),
        new Entry(1673, "Phetsarath", "ofl/phetsarath/Phetsarath-Regular.ttf", true),
        new Entry(1674, "Phudu", "ofl/phudu/Phudu[wght].ttf", true),
        new Entry(1675, "Piazzolla", "ofl/piazzolla/Piazzolla[opsz,wght].ttf", true),
        new Entry(1676, "Piedra", "ofl/piedra/Piedra-Regular.ttf", true),
        new Entry(1677, "Pixelify Sans", "ofl/pixelifysans/PixelifySans[wght].ttf", true),
        new Entry(1678, "Plaster", "ofl/plaster/Plaster-Regular.ttf", true),
        new Entry(1679, "Platypi", "ofl/platypi/Platypi[wght].ttf", true),
        new Entry(1680, "Playball", "ofl/playball/Playball-Regular.ttf", true),
        new Entry(1681, "Playfair Display SC", "ofl/playfairdisplaysc/PlayfairDisplaySC-Regular.ttf", true),
        new Entry(1682, "Playpen Sans Deva", "ofl/playpensansdeva/PlaypenSansDeva[wght].ttf", true),
        new Entry(1683, "Playwrite AR Guides", "ofl/playwritearguides/PlaywriteARGuides-Regular.ttf", true),
        new Entry(1684, "Playwrite AT Guides", "ofl/playwriteatguides/PlaywriteATGuides-Regular.ttf", true),
        new Entry(1685, "Playwrite AUNSW Guides", "ofl/playwriteaunswguides/PlaywriteAUNSWGuides-Regular.ttf", true),
        new Entry(1686, "Playwrite AUQLD", "ofl/playwriteauqld/PlaywriteAUQLD[wght].ttf", true),
        new Entry(1687, "Playwrite AUQLD Guides", "ofl/playwriteauqldguides/PlaywriteAUQLDGuides-Regular.ttf", true),
        new Entry(1688, "Playwrite AUTAS Guides", "ofl/playwriteautasguides/PlaywriteAUTASGuides-Regular.ttf", true),
        new Entry(1689, "Playwrite AUVIC Guides", "ofl/playwriteauvicguides/PlaywriteAUVICGuides-Regular.ttf", true),
        new Entry(1690, "Playwrite BEWAL", "ofl/playwritebewal/PlaywriteBEWAL[wght].ttf", true),
        new Entry(1691, "Playwrite BR", "ofl/playwritebr/PlaywriteBR[wght].ttf", true),
        new Entry(1692, "Playwrite CA", "ofl/playwriteca/PlaywriteCA[wght].ttf", true),
        new Entry(1693, "Playwrite CL", "ofl/playwritecl/PlaywriteCL[wght].ttf", true),
        new Entry(1694, "Playwrite CO Guides", "ofl/playwritecoguides/PlaywriteCOGuides-Regular.ttf", true),
        new Entry(1695, "Playwrite CU", "ofl/playwritecu/PlaywriteCU[wght].ttf", true),
        new Entry(1696, "Playwrite CU Guides", "ofl/playwritecuguides/PlaywriteCUGuides-Regular.ttf", true),
        new Entry(1697, "Playwrite CZ", "ofl/playwritecz/PlaywriteCZ[wght].ttf", true),
        new Entry(1698, "Playwrite CZ Guides", "ofl/playwriteczguides/PlaywriteCZGuides-Regular.ttf", true),
        new Entry(1699, "Playwrite DE Grund Guides", "ofl/playwritedegrundguides/PlaywriteDEGrundGuides-Regular.ttf", true),
        new Entry(1700, "Playwrite DELA", "ofl/playwritedela/PlaywriteDELA[wght].ttf", true),
        new Entry(1701, "Playwrite DELA Guides", "ofl/playwritedelaguides/PlaywriteDELAGuides-Regular.ttf", true),
        new Entry(1702, "Playwrite DESAS", "ofl/playwritedesas/PlaywriteDESAS[wght].ttf", true),
        new Entry(1703, "Playwrite DESAS Guides", "ofl/playwritedesasguides/PlaywriteDESASGuides-Regular.ttf", true),
        new Entry(1704, "Playwrite DEVA", "ofl/playwritedeva/PlaywriteDEVA[wght].ttf", true),
        new Entry(1705, "Playwrite DEVA Guides", "ofl/playwritedevaguides/PlaywriteDEVAGuides-Regular.ttf", true),
        new Entry(1706, "Playwrite DK Loopet Guides", "ofl/playwritedkloopetguides/PlaywriteDKLoopetGuides-Regular.ttf", true),
        new Entry(1707, "Playwrite DK Uloopet", "ofl/playwritedkuloopet/PlaywriteDKUloopet[wght].ttf", true),
        new Entry(1708, "Playwrite ES Deco Guides", "ofl/playwriteesdecoguides/PlaywriteESDecoGuides-Regular.ttf", true),
        new Entry(1709, "Playwrite FR Moderne", "ofl/playwritefrmoderne/PlaywriteFRModerne[wght].ttf", true),
        new Entry(1710, "Playwrite FR Trad", "ofl/playwritefrtrad/PlaywriteFRTrad[wght].ttf", true),
        new Entry(1711, "Playwrite GBJ", "ofl/playwritegbj/PlaywriteGBJ[wght].ttf", true),
        new Entry(1712, "Playwrite GBS", "ofl/playwritegbs/PlaywriteGBS[wght].ttf", true),
        new Entry(1713, "Playwrite GBS Guides", "ofl/playwritegbsguides/PlaywriteGBSGuides-Regular.ttf", true),
        new Entry(1714, "Playwrite HR", "ofl/playwritehr/PlaywriteHR[wght].ttf", true),
        new Entry(1715, "Playwrite HR Lijeva", "ofl/playwritehrlijeva/PlaywriteHRLijeva[wght].ttf", true),
        new Entry(1716, "Playwrite HR Lijeva Guides", "ofl/playwritehrlijevaguides/PlaywriteHRLijevaGuides-Regular.ttf", true),
        new Entry(1717, "Playwrite HU Guides", "ofl/playwritehuguides/PlaywriteHUGuides-Regular.ttf", true),
        new Entry(1718, "Playwrite ID", "ofl/playwriteid/PlaywriteID[wght].ttf", true),
        new Entry(1719, "Playwrite ID Guides", "ofl/playwriteidguides/PlaywriteIDGuides-Regular.ttf", true),
        new Entry(1720, "Playwrite IE", "ofl/playwriteie/PlaywriteIE[wght].ttf", true),
        new Entry(1721, "Playwrite IE Guides", "ofl/playwriteieguides/PlaywriteIEGuides-Regular.ttf", true),
        new Entry(1722, "Playwrite IN", "ofl/playwritein/PlaywriteIN[wght].ttf", true),
        new Entry(1723, "Playwrite IS Guides", "ofl/playwriteisguides/PlaywriteISGuides-Regular.ttf", true),
        new Entry(1724, "Playwrite IT Moderna", "ofl/playwriteitmoderna/PlaywriteITModerna[wght].ttf", true),
        new Entry(1725, "Playwrite IT Trad", "ofl/playwriteittrad/PlaywriteITTrad[wght].ttf", true),
        new Entry(1726, "Playwrite MX", "ofl/playwritemx/PlaywriteMX[wght].ttf", true),
        new Entry(1727, "Playwrite NG Modern", "ofl/playwritengmodern/PlaywriteNGModern[wght].ttf", true),
        new Entry(1728, "Playwrite NG Modern Guides", "ofl/playwritengmodernguides/PlaywriteNGModernGuides-Regular.ttf", true),
        new Entry(1729, "Playwrite NL", "ofl/playwritenl/PlaywriteNL[wght].ttf", true),
        new Entry(1730, "Playwrite NL Guides", "ofl/playwritenlguides/PlaywriteNLGuides-Regular.ttf", true),
        new Entry(1731, "Playwrite NO", "ofl/playwriteno/PlaywriteNO[wght].ttf", true),
        new Entry(1732, "Playwrite NZ", "ofl/playwritenz/PlaywriteNZ[wght].ttf", true),
        new Entry(1733, "Playwrite NZ Basic", "ofl/playwritenzbasic/PlaywriteNZBasic[wght].ttf", true),
        new Entry(1734, "Playwrite NZ Guides", "ofl/playwritenzguides/PlaywriteNZGuides-Regular.ttf", true),
        new Entry(1735, "Playwrite PE Guides", "ofl/playwritepeguides/PlaywritePEGuides-Regular.ttf", true),
        new Entry(1736, "Playwrite PL", "ofl/playwritepl/PlaywritePL[wght].ttf", true),
        new Entry(1737, "Playwrite PL Guides", "ofl/playwriteplguides/PlaywritePLGuides-Regular.ttf", true),
        new Entry(1738, "Playwrite PT", "ofl/playwritept/PlaywritePT[wght].ttf", true),
        new Entry(1739, "Playwrite PT Guides", "ofl/playwriteptguides/PlaywritePTGuides-Regular.ttf", true),
        new Entry(1740, "Playwrite RO", "ofl/playwritero/PlaywriteRO[wght].ttf", true),
        new Entry(1741, "Playwrite RO Guides", "ofl/playwriteroguides/PlaywriteROGuides-Regular.ttf", true),
        new Entry(1742, "Playwrite SK Guides", "ofl/playwriteskguides/PlaywriteSKGuides-Regular.ttf", true),
        new Entry(1743, "Playwrite TZ Guides", "ofl/playwritetzguides/PlaywriteTZGuides-Regular.ttf", true),
        new Entry(1744, "Playwrite US Modern", "ofl/playwriteusmodern/PlaywriteUSModern[wght].ttf", true),
        new Entry(1745, "Playwrite VN Guides", "ofl/playwritevnguides/PlaywriteVNGuides-Regular.ttf", true),
        new Entry(1746, "Playwrite ZA", "ofl/playwriteza/PlaywriteZA[wght].ttf", true),
        new Entry(1747, "Playwrite ZA Guides", "ofl/playwritezaguides/PlaywriteZAGuides-Regular.ttf", true),
        new Entry(1748, "Pliant", "ofl/pliant/Pliant[wdth,wght].ttf", true),
        new Entry(1749, "Plus Jakarta Sans", "ofl/plusjakartasans/PlusJakartaSans[wght].ttf", true),
        new Entry(1750, "Pochaevsk", "ofl/pochaevsk/Pochaevsk-Regular.ttf", true),
        new Entry(1751, "Poiret One", "ofl/poiretone/PoiretOne-Regular.ttf", true),
        new Entry(1752, "Poller One", "ofl/pollerone/PollerOne.ttf", true),
        new Entry(1753, "Pompiere", "ofl/pompiere/Pompiere-Regular.ttf", true),
        new Entry(1754, "Ponnala", "ofl/ponnala/Ponnala-Regular.ttf", true),
        new Entry(1755, "Ponomar", "ofl/ponomar/Ponomar-Regular.ttf", true),
        new Entry(1756, "Poor Story", "ofl/poorstory/PoorStory-Regular.ttf", true),
        new Entry(1757, "Port Lligat Sans", "ofl/portlligatsans/PortLligatSans-Regular.ttf", true),
        new Entry(1758, "Port Lligat Slab", "ofl/portlligatslab/PortLligatSlab-Regular.ttf", true),
        new Entry(1759, "Porter Sans Block", "ofl/portersansblock/PorterSansBlock-Regular.ttf", true),
        new Entry(1760, "Pragati Narrow", "ofl/pragatinarrow/PragatiNarrow-Regular.ttf", true),
        new Entry(1761, "Press Start2 P", "ofl/pressstart2p/PressStart2P-Regular.ttf", true),
        new Entry(1762, "Pridi", "ofl/pridi/Pridi-Regular.ttf", true),
        new Entry(1763, "Prociono", "ofl/prociono/Prociono-Regular.ttf", true),
        new Entry(1764, "Prompt", "ofl/prompt/Prompt-Regular.ttf", true),
        new Entry(1765, "Prosto One", "ofl/prostoone/ProstoOne-Regular.ttf", true),
        new Entry(1766, "Protest Guerrilla", "ofl/protestguerrilla/ProtestGuerrilla-Regular.ttf", true),
        new Entry(1767, "Protest Revolution", "ofl/protestrevolution/ProtestRevolution-Regular.ttf", true),
        new Entry(1768, "Protest Riot", "ofl/protestriot/ProtestRiot-Regular.ttf", true),
        new Entry(1769, "Proza Libre", "ofl/prozalibre/ProzaLibre-Regular.ttf", true),
        new Entry(1770, "PT Sans-Caption-Web", "ofl/ptsanscaption/PT_Sans-Caption-Web-Regular.ttf", true),
        new Entry(1771, "PT Sans-Web", "ofl/ptsans/PT_Sans-Web-Regular.ttf", true),
        new Entry(1772, "PTM55 FT", "ofl/ptmono/PTM55FT.ttf", true),
        new Entry(1773, "Public Sans", "ofl/publicsans/PublicSans[wght].ttf", true),
        new Entry(1774, "Puritan", "ofl/puritan/Puritan-Regular.ttf", true),
        new Entry(1775, "Purple Purse", "ofl/purplepurse/PurplePurse-Regular.ttf", true),
        new Entry(1776, "Pushster", "ofl/pushster/Pushster-Regular.ttf", true),
        new Entry(1777, "Quando", "ofl/quando/Quando-Regular.ttf", true),
        new Entry(1778, "Quantico", "ofl/quantico/Quantico-Regular.ttf", true),
        new Entry(1779, "Quattrocento Sans", "ofl/quattrocentosans/QuattrocentoSans-Regular.ttf", true),
        new Entry(1780, "Quicksand", "ofl/quicksand/Quicksand[wght].ttf", true),
        new Entry(1781, "Quintessential", "ofl/quintessential/Quintessential-Regular.ttf", true),
        new Entry(1782, "Qwitcher Grypen", "ofl/qwitchergrypen/QwitcherGrypen-Regular.ttf", true),
        new Entry(1783, "Racing Sans One", "ofl/racingsansone/RacingSansOne-Regular.ttf", true),
        new Entry(1784, "Radio Canada", "ofl/radiocanada/RadioCanada[wdth,wght].ttf", true),
        new Entry(1785, "Radio Canada Big", "ofl/radiocanadabig/RadioCanadaBig[wght].ttf", true),
        new Entry(1786, "Raleway", "ofl/raleway/Raleway[wght].ttf", true),
        new Entry(1787, "Ramabhadra", "ofl/ramabhadra/Ramabhadra-Regular.ttf", true),
        new Entry(1788, "Ramaraja", "ofl/ramaraja/Ramaraja-Regular.ttf", true),
        new Entry(1789, "Rambla", "ofl/rambla/Rambla-Regular.ttf", true),
        new Entry(1790, "Rammetto One", "ofl/rammettoone/RammettoOne-Regular.ttf", true),
        new Entry(1791, "Ramsina", "ofl/ramsina/Ramsina-Regular.ttf", true),
        new Entry(1792, "Ranchers", "ofl/ranchers/Ranchers-Regular.ttf", true),
        new Entry(1793, "Rationale", "ofl/rationale/Rationale-Regular.ttf", true),
        new Entry(1794, "Red Hat Display", "ofl/redhatdisplay/RedHatDisplay[wght].ttf", true),
        new Entry(1795, "Red Hat Mono", "ofl/redhatmono/RedHatMono[wght].ttf", true),
        new Entry(1796, "Red Rose", "ofl/redrose/RedRose[wght].ttf", true),
        new Entry(1797, "Reddit Mono", "ofl/redditmono/RedditMono[wght].ttf", true),
        new Entry(1798, "Reddit Sans Condensed", "ofl/redditsanscondensed/RedditSansCondensed[wght].ttf", true),
        new Entry(1799, "Reem Kufi Fun", "ofl/reemkufifun/ReemKufiFun[wght].ttf", true),
        new Entry(1800, "Reem Kufi Ink", "ofl/reemkufiink/ReemKufiInk-Regular.ttf", true),
        new Entry(1801, "Reggae One", "ofl/reggaeone/ReggaeOne-Regular.ttf", true),
        new Entry(1802, "REM", "ofl/rem/REM[wght].ttf", true),
        new Entry(1803, "Revalia", "ofl/revalia/Revalia-Regular.ttf", true),
        new Entry(1804, "Rhodium Libre", "ofl/rhodiumlibre/RhodiumLibre-Regular.ttf", true),
        new Entry(1805, "Ribeye Marrow", "ofl/ribeyemarrow/RibeyeMarrow-Regular.ttf", true),
        new Entry(1806, "Road Rage", "ofl/roadrage/RoadRage-Regular.ttf", true),
        new Entry(1807, "Roboto", "ofl/roboto/Roboto[wdth,wght].ttf", true),
        new Entry(1808, "Roboto Condensed", "ofl/robotocondensed/RobotoCondensed[wght].ttf", true),
        new Entry(1809, "Roboto Flex", "ofl/robotoflex/RobotoFlex[GRAD,XOPQ,XTRA,YOPQ,YTAS,YTDE,YTFI,YTLC,YTUC,opsz,slnt,wdth,wght].ttf", true),
        new Entry(1810, "Roboto Mono", "ofl/robotomono/RobotoMono[wght].ttf", true),
        new Entry(1811, "Roboto Serif", "ofl/robotoserif/RobotoSerif[GRAD,opsz,wdth,wght].ttf", true),
        new Entry(1812, "Rock3 D", "ofl/rock3d/Rock3D-Regular.ttf", true),
        new Entry(1813, "Rockn Roll One", "ofl/rocknrollone/RocknRollOne-Regular.ttf", true),
        new Entry(1814, "Rokkitt", "ofl/rokkitt/Rokkitt[wght].ttf", true),
        new Entry(1815, "Romanesco", "ofl/romanesco/Romanesco-Regular.ttf", true),
        new Entry(1816, "Rosario", "ofl/rosario/Rosario[wght].ttf", true),
        new Entry(1817, "Rosarivo", "ofl/rosarivo/Rosarivo-Regular.ttf", true),
        new Entry(1818, "Rouge Script", "ofl/rougescript/RougeScript-Regular.ttf", true),
        new Entry(1819, "Rounded Mplus1c", "ofl/roundedmplus1c/RoundedMplus1c-Regular.ttf", true),
        new Entry(1820, "Rozha One", "ofl/rozhaone/RozhaOne-Regular.ttf", true),
        new Entry(1821, "Rubik", "ofl/rubik/Rubik[wght].ttf", true),
        new Entry(1822, "Rubik Broken Fax", "ofl/rubikbrokenfax/RubikBrokenFax-Regular.ttf", true),
        new Entry(1823, "Rubik Burned", "ofl/rubikburned/RubikBurned-Regular.ttf", true),
        new Entry(1824, "Rubik Dirt", "ofl/rubikdirt/RubikDirt-Regular.ttf", true),
        new Entry(1825, "Rubik Doodle Triangles", "ofl/rubikdoodletriangles/RubikDoodleTriangles-Regular.ttf", true),
        new Entry(1826, "Rubik Gemstones", "ofl/rubikgemstones/RubikGemstones-Regular.ttf", true),
        new Entry(1827, "Rubik Iso", "ofl/rubikiso/RubikIso-Regular.ttf", true),
        new Entry(1828, "Rubik Lines", "ofl/rubiklines/RubikLines-Regular.ttf", true),
        new Entry(1829, "Rubik Maps", "ofl/rubikmaps/RubikMaps-Regular.ttf", true),
        new Entry(1830, "Rubik Microbe", "ofl/rubikmicrobe/RubikMicrobe-Regular.ttf", true),
        new Entry(1831, "Rubik Mono One", "ofl/rubikmonoone/RubikMonoOne-Regular.ttf", true),
        new Entry(1832, "Rubik Scribble", "ofl/rubikscribble/RubikScribble-Regular.ttf", true),
        new Entry(1833, "Rubik Spray Paint", "ofl/rubikspraypaint/RubikSprayPaint-Regular.ttf", true),
        new Entry(1834, "Rubik Storm", "ofl/rubikstorm/RubikStorm-Regular.ttf", true),
        new Entry(1835, "Rubik Wet Paint", "ofl/rubikwetpaint/RubikWetPaint-Regular.ttf", true),
        new Entry(1836, "Ruda", "ofl/ruda/Ruda[wght].ttf", true),
        new Entry(1837, "Rufina", "ofl/rufina/Rufina-Regular.ttf", true),
        new Entry(1838, "Ruluko", "ofl/ruluko/Ruluko-Regular.ttf", true),
        new Entry(1839, "Ruslan Display", "ofl/ruslandisplay/RuslanDisplay-Regular.ttf", true),
        new Entry(1840, "Russo One", "ofl/russoone/RussoOne-Regular.ttf", true),
        new Entry(1841, "Ruthie", "ofl/ruthie/Ruthie-Regular.ttf", true),
        new Entry(1842, "Ruwudu", "ofl/ruwudu/Ruwudu-Regular.ttf", true),
        new Entry(1843, "Rye", "ofl/rye/Rye-Regular.ttf", true),
        new Entry(1844, "Sacramento", "ofl/sacramento/Sacramento-Regular.ttf", true),
        new Entry(1845, "Saira", "ofl/saira/Saira[wdth,wght].ttf", true),
        new Entry(1846, "Saira Condensed", "ofl/sairacondensed/SairaCondensed-Regular.ttf", true),
        new Entry(1847, "Saira Semi Condensed", "ofl/sairasemicondensed/SairaSemiCondensed-Regular.ttf", true),
        new Entry(1848, "Saira Stencil", "ofl/sairastencil/SairaStencil[wdth,wght].ttf", true),
        new Entry(1849, "Sanchez", "ofl/sanchez/Sanchez-Regular.ttf", true),
        new Entry(1850, "Sansation", "ofl/sansation/Sansation-Regular.ttf", true),
        new Entry(1851, "Sansita", "ofl/sansita/Sansita-Regular.ttf", true),
        new Entry(1852, "Sansita One", "ofl/sansitaone/SansitaOne-Regular.ttf", true),
        new Entry(1853, "Sansita Swashed", "ofl/sansitaswashed/SansitaSwashed[wght].ttf", true),
        new Entry(1854, "Sarabun", "ofl/sarabun/Sarabun-Regular.ttf", true),
        new Entry(1855, "Sarpanch", "ofl/sarpanch/Sarpanch-Regular.ttf", true),
        new Entry(1856, "Sawarabi Gothic", "ofl/sawarabigothic/SawarabiGothic-Regular.ttf", true),
        new Entry(1857, "Sawarabi Mincho", "ofl/sawarabimincho/SawarabiMincho-Regular.ttf", true),
        new Entry(1858, "Scheherazade New", "ofl/scheherazadenew/ScheherazadeNew-Regular.ttf", true),
        new Entry(1859, "Schibsted Grotesk", "ofl/schibstedgrotesk/SchibstedGrotesk[wght].ttf", true),
        new Entry(1860, "Science Gothic", "ofl/sciencegothic/ScienceGothic[CTRS,slnt,wdth,wght].ttf", true),
        new Entry(1861, "Seaweed Script", "ofl/seaweedscript/SeaweedScript-Regular.ttf", true),
        new Entry(1862, "Secular One", "ofl/secularone/SecularOne-Regular.ttf", true),
        new Entry(1863, "Sedgwick Ave Display", "ofl/sedgwickavedisplay/SedgwickAveDisplay-Regular.ttf", true),
        new Entry(1864, "Sen", "ofl/sen/Sen[wght].ttf", true),
        new Entry(1865, "Send Flowers", "ofl/sendflowers/SendFlowers-Regular.ttf", true),
        new Entry(1866, "Shadows Into Light", "ofl/shadowsintolight/ShadowsIntoLight.ttf", true),
        new Entry(1867, "Shadows Into Light Two", "ofl/shadowsintolighttwo/ShadowsIntoLightTwo-Regular.ttf", true),
        new Entry(1868, "Shalimar", "ofl/shalimar/Shalimar-Regular.ttf", true),
        new Entry(1869, "Shantell Sans", "ofl/shantellsans/ShantellSans[BNCE,INFM,SPAC,wght].ttf", true),
        new Entry(1870, "Shanti", "ofl/shanti/Shanti-Regular.ttf", true),
        new Entry(1871, "Share", "ofl/share/Share-Regular.ttf", true),
        new Entry(1872, "Shizuru", "ofl/shizuru/Shizuru-Regular.ttf", true),
        new Entry(1873, "Shojumaru", "ofl/shojumaru/Shojumaru-Regular.ttf", true),
        new Entry(1874, "Short Stack", "ofl/shortstack/ShortStack-Regular.ttf", true),
        new Entry(1875, "Sigmar", "ofl/sigmar/Sigmar-Regular.ttf", true),
        new Entry(1876, "Signika", "ofl/signika/Signika[GRAD,wght].ttf", true),
        new Entry(1877, "Signika Negative", "ofl/signikanegative/SignikaNegative[wght].ttf", true),
        new Entry(1878, "Simonetta", "ofl/simonetta/Simonetta-Regular.ttf", true),
        new Entry(1879, "Single Day", "ofl/singleday/SingleDay-Regular.ttf", true),
        new Entry(1880, "Sirin Stencil", "ofl/sirinstencil/SirinStencil-Regular.ttf", true),
        new Entry(1881, "Sirivennela", "ofl/sirivennela/Sirivennela-Regular.ttf", true),
        new Entry(1882, "Sitara", "ofl/sitara/Sitara-Regular.ttf", true),
        new Entry(1883, "Six Caps", "ofl/sixcaps/SixCaps.ttf", true),
        new Entry(1884, "Skranji", "ofl/skranji/Skranji-Regular.ttf", true),
        new Entry(1885, "Slabo13px", "ofl/slabo13px/Slabo13px-Regular.ttf", true),
        new Entry(1886, "Slabo27px", "ofl/slabo27px/Slabo27px-Regular.ttf", true),
        new Entry(1887, "Slackside One", "ofl/slacksideone/SlacksideOne-Regular.ttf", true),
        new Entry(1888, "Smythe", "ofl/smythe/Smythe-Regular.ttf", true),
        new Entry(1889, "Sniglet", "ofl/sniglet/Sniglet-Regular.ttf", true),
        new Entry(1890, "Snowburst One", "ofl/snowburstone/SnowburstOne-Regular.ttf", true),
        new Entry(1891, "Sofadi One", "ofl/sofadione/SofadiOne-Regular.ttf", true),
        new Entry(1892, "Solitreo", "ofl/solitreo/Solitreo-Regular.ttf", true),
        new Entry(1893, "Sometype Mono", "ofl/sometypemono/SometypeMono[wght].ttf", true),
        new Entry(1894, "Song Myung", "ofl/songmyung/SongMyung-Regular.ttf", true),
        new Entry(1895, "Sono", "ofl/sono/Sono[MONO,wght].ttf", true),
        new Entry(1896, "Sonsie One", "ofl/sonsieone/SonsieOne-Regular.ttf", true),
        new Entry(1897, "Sora", "ofl/sora/Sora[wght].ttf", true),
        new Entry(1898, "Sorts Mill Goudy", "ofl/sortsmillgoudy/SortsMillGoudy-Regular.ttf", true),
        new Entry(1899, "Source Sans3", "ofl/sourcesans3/SourceSans3[wght].ttf", true),
        new Entry(1900, "Source Serif4", "ofl/sourceserif4/SourceSerif4[opsz,wght].ttf", true),
        new Entry(1901, "Space Grotesk", "ofl/spacegrotesk/SpaceGrotesk[wght].ttf", true),
        new Entry(1902, "Space Mono", "ofl/spacemono/SpaceMono-Regular.ttf", true),
        new Entry(1903, "Special Gothic", "ofl/specialgothic/SpecialGothic[wdth,wght].ttf", true),
        new Entry(1904, "Special Gothic Condensed One", "ofl/specialgothiccondensedone/SpecialGothicCondensedOne-Regular.ttf", true),
        new Entry(1905, "Special Gothic Expanded One", "ofl/specialgothicexpandedone/SpecialGothicExpandedOne-Regular.ttf", true),
        new Entry(1906, "Spicy Rice", "ofl/spicyrice/SpicyRice-Regular.ttf", true),
        new Entry(1907, "Spinnaker", "ofl/spinnaker/Spinnaker-Regular.ttf", true),
        new Entry(1908, "Spirax", "ofl/spirax/Spirax-Regular.ttf", true),
        new Entry(1909, "Spline Sans", "ofl/splinesans/SplineSans[wght].ttf", true),
        new Entry(1910, "Spline Sans Mono", "ofl/splinesansmono/SplineSansMono[wght].ttf", true),
        new Entry(1911, "Square Peg", "ofl/squarepeg/SquarePeg-Regular.ttf", true),
        new Entry(1912, "Sree Krushnadevaraya", "ofl/sreekrushnadevaraya/SreeKrushnadevaraya-Regular.ttf", true),
        new Entry(1913, "Srisakdi", "ofl/srisakdi/Srisakdi-Regular.ttf", true),
        new Entry(1914, "Staatliches", "ofl/staatliches/Staatliches-Regular.ttf", true),
        new Entry(1915, "Stack Sans Headline", "ofl/stacksansheadline/StackSansHeadline[wght].ttf", true),
        new Entry(1916, "Stack Sans Notch", "ofl/stacksansnotch/StackSansNotch[wght].ttf", true),
        new Entry(1917, "Stick No Bills", "ofl/sticknobills/StickNoBills[wght].ttf", true),
        new Entry(1918, "Stint Ultra Condensed", "ofl/stintultracondensed/StintUltraCondensed-Regular.ttf", true),
        new Entry(1919, "STIX Two Text", "ofl/stixtwotext/STIXTwoText[wght].ttf", true),
        new Entry(1920, "Stoke", "ofl/stoke/Stoke-Regular.ttf", true),
        new Entry(1921, "Story Script", "ofl/storyscript/StoryScript-Regular.ttf", true),
        new Entry(1922, "Strait", "ofl/strait/Strait-Regular.ttf", true),
        new Entry(1923, "Strichpunkt Sans", "ofl/strichpunktsans/StrichpunktSans[wdth,wght].ttf", true),
        new Entry(1924, "Strong", "ofl/strong/Strong-Regular.ttf", true),
        new Entry(1925, "Style Script", "ofl/stylescript/StyleScript-Regular.ttf", true),
        new Entry(1926, "Sunflower", "ofl/sunflower/Sunflower-Light.ttf", true),
        new Entry(1927, "Supermercado One", "ofl/supermercadoone/SupermercadoOne-Regular.ttf", true),
        new Entry(1928, "Sura", "ofl/sura/Sura-Regular.ttf", true),
        new Entry(1929, "Suranna", "ofl/suranna/Suranna-Regular.ttf", true),
        new Entry(1930, "Suravaram", "ofl/suravaram/Suravaram-Regular.ttf", true),
        new Entry(1931, "Suwannaphum", "ofl/suwannaphum/Suwannaphum-Regular.ttf", true),
        new Entry(1932, "Syne Mono", "ofl/synemono/SyneMono-Regular.ttf", true),
        new Entry(1933, "Tac One", "ofl/tacone/TacOne-Regular.ttf", true),
        new Entry(1934, "Tagesschrift", "ofl/tagesschrift/Tagesschrift-Regular.ttf", true),
        new Entry(1935, "Tajawal", "ofl/tajawal/Tajawal-Regular.ttf", true),
        new Entry(1936, "Taprom", "ofl/taprom/Taprom-Regular.ttf", true),
        new Entry(1937, "TASA Explorer", "ofl/tasaexplorer/TASAExplorer[wght].ttf", true),
        new Entry(1938, "Tauri", "ofl/tauri/Tauri-Regular.ttf", true),
        new Entry(1939, "Taviraj", "ofl/taviraj/Taviraj-Regular.ttf", true),
        new Entry(1940, "Teachers", "ofl/teachers/Teachers[wght].ttf", true),
        new Entry(1941, "Teko", "ofl/teko/Teko[wght].ttf", true),
        new Entry(1942, "Tenali Ramakrishna", "ofl/tenaliramakrishna/TenaliRamakrishna-Regular.ttf", true),
        new Entry(1943, "Tenor Sans", "ofl/tenorsans/TenorSans-Regular.ttf", true),
        new Entry(1944, "Text Me One", "ofl/textmeone/TextMeOne-Regular.ttf", true),
        new Entry(1945, "Texturina", "ofl/texturina/Texturina[opsz,wght].ttf", true),
        new Entry(1946, "Thabit-Oblique", "ofl/thabit/Thabit-Oblique.ttf", true),
        new Entry(1947, "Tharlon", "ofl/tharlon/Tharlon-Regular.ttf", true),
        new Entry(1948, "Thasadith", "ofl/thasadith/Thasadith-Regular.ttf", true),
        new Entry(1949, "The Nautigal", "ofl/thenautigal/TheNautigal-Regular.ttf", true),
        new Entry(1950, "Tilt Neon", "ofl/tiltneon/TiltNeon[XROT,YROT].ttf", true),
        new Entry(1951, "Tinos", "ofl/tinos/Tinos-Regular.ttf", true),
        new Entry(1952, "Tirra", "ofl/tirra/Tirra-Regular.ttf", true),
        new Entry(1953, "Titan One", "ofl/titanone/TitanOne-Regular.ttf", true),
        new Entry(1954, "Titillium Web", "ofl/titilliumweb/TitilliumWeb-Regular.ttf", true),
        new Entry(1955, "Tomorrow", "ofl/tomorrow/Tomorrow-Regular.ttf", true),
        new Entry(1956, "Tourney", "ofl/tourney/Tourney[wdth,wght].ttf", true),
        new Entry(1957, "Trade Winds", "ofl/tradewinds/TradeWinds-Regular.ttf", true),
        new Entry(1958, "Train One", "ofl/trainone/TrainOne-Regular.ttf", true),
        new Entry(1959, "Trirong", "ofl/trirong/Trirong-Regular.ttf", true),
        new Entry(1960, "Trykker", "ofl/trykker/Trykker-Regular.ttf", true),
        new Entry(1961, "Tsukimi Rounded", "ofl/tsukimirounded/TsukimiRounded-Regular.ttf", true),
        new Entry(1962, "Tuffy", "ofl/tuffy/Tuffy-Regular.ttf", true),
        new Entry(1963, "Tulpen One", "ofl/tulpenone/TulpenOne-Regular.ttf", true),
        new Entry(1964, "Twinkle Star", "ofl/twinklestar/TwinkleStar-Regular.ttf", true),
        new Entry(1965, "Uchen", "ofl/uchen/Uchen-Regular.ttf", true),
        new Entry(1966, "Unbounded", "ofl/unbounded/Unbounded[wght].ttf", true),
        new Entry(1967, "Uncial Antiqua", "ofl/uncialantiqua/UncialAntiqua-Regular.ttf", true),
        new Entry(1968, "Underdog", "ofl/underdog/Underdog-Regular.ttf", true),
        new Entry(1969, "Unica One", "ofl/unicaone/UnicaOne-Regular.ttf", true),
        new Entry(1970, "Unifraktur Cook", "ofl/unifrakturcook/UnifrakturCook-Bold.ttf", true),
        new Entry(1971, "Unifraktur Maguntia-Book", "ofl/unifrakturmaguntia/UnifrakturMaguntia-Book.ttf", true),
        new Entry(1972, "Unna", "ofl/unna/Unna-Regular.ttf", true),
        new Entry(1973, "Updock", "ofl/updock/Updock-Regular.ttf", true),
        new Entry(1974, "Urbanist", "ofl/urbanist/Urbanist[wght].ttf", true),
        new Entry(1975, "Valley Sans", "ofl/valleysans/ValleySans[wght].ttf", true),
        new Entry(1976, "Vampiro One", "ofl/vampiroone/VampiroOne-Regular.ttf", true),
        new Entry(1977, "Varela", "ofl/varela/Varela-Regular.ttf", true),
        new Entry(1978, "Varela Round", "ofl/varelaround/VarelaRound-Regular.ttf", true),
        new Entry(1979, "Varta", "ofl/varta/Varta[wght].ttf", true),
        new Entry(1980, "Vast Shadow", "ofl/vastshadow/VastShadow-Regular.ttf", true),
        new Entry(1981, "Vend Sans", "ofl/vendsans/VendSans[wght].ttf", true),
        new Entry(1982, "Vesper Libre", "ofl/vesperlibre/VesperLibre-Regular.ttf", true),
        new Entry(1983, "Viaoda Libre", "ofl/viaodalibre/ViaodaLibre-Regular.ttf", true),
        new Entry(1984, "Vibes", "ofl/vibes/Vibes-Regular.ttf", true),
        new Entry(1985, "Vidaloka", "ofl/vidaloka/Vidaloka-Regular.ttf", true),
        new Entry(1986, "Vina Sans", "ofl/vinasans/VinaSans-Regular.ttf", true),
        new Entry(1987, "Volkhov", "ofl/volkhov/Volkhov-Regular.ttf", true),
        new Entry(1988, "Vollkorn", "ofl/vollkorn/Vollkorn[wght].ttf", true),
        new Entry(1989, "Vujahday Script", "ofl/vujahdayscript/VujahdayScript-Regular.ttf", true),
        new Entry(1990, "Waitingforthe Sunrise", "ofl/waitingforthesunrise/WaitingfortheSunrise.ttf", true),
        new Entry(1991, "Wallpoet", "ofl/wallpoet/Wallpoet-Regular.ttf", true),
        new Entry(1992, "Warnes", "ofl/warnes/Warnes-Regular.ttf", true),
        new Entry(1993, "Water Brush", "ofl/waterbrush/WaterBrush-Regular.ttf", true),
        new Entry(1994, "Wavefont", "ofl/wavefont/Wavefont[ROND,YELA,wght].ttf", true),
        new Entry(1995, "Wellfleet", "ofl/wellfleet/Wellfleet-Regular.ttf", true),
        new Entry(1996, "Wendy One", "ofl/wendyone/WendyOne-Regular.ttf", true),
        new Entry(1997, "Wind Song", "ofl/windsong/WindSong-Regular.ttf", true),
        new Entry(1998, "Wittgenstein", "ofl/wittgenstein/Wittgenstein[wght].ttf", true),
        new Entry(1999, "Workbench", "ofl/workbench/Workbench[BLED,SCAN].ttf", true),
        new Entry(2000, "Xanh Mono", "ofl/xanhmono/XanhMono-Regular.ttf", true),
        new Entry(2001, "Xmind", "ofl/xmind/Xmind[wght].ttf", true),
        new Entry(2002, "Yanone Kaffeesatz", "ofl/yanonekaffeesatz/YanoneKaffeesatz[wght].ttf", true),
        new Entry(2003, "Yarndings12", "ofl/yarndings12/Yarndings12-Regular.ttf", true),
        new Entry(2004, "Yarndings12 Charted", "ofl/yarndings12charted/Yarndings12Charted-Regular.ttf", true),
        new Entry(2005, "Yarndings20 Charted", "ofl/yarndings20charted/Yarndings20Charted-Regular.ttf", true),
        new Entry(2006, "Yatra One", "ofl/yatraone/YatraOne-Regular.ttf", true),
        new Entry(2007, "Yeon Sung", "ofl/yeonsung/YeonSung-Regular.ttf", true),
        new Entry(2008, "Yesteryear", "ofl/yesteryear/Yesteryear-Regular.ttf", true),
        new Entry(2009, "Yinmar", "ofl/yinmar/Yinmar-Regular.ttf", true),
        new Entry(2010, "Yomogi", "ofl/yomogi/Yomogi-Regular.ttf", true),
        new Entry(2011, "Ysabeau", "ofl/ysabeau/Ysabeau[wght].ttf", true),
        new Entry(2012, "Ysabeau Infant", "ofl/ysabeauinfant/YsabeauInfant[wght].ttf", true),
        new Entry(2013, "Ysabeau SC", "ofl/ysabeausc/YsabeauSC[wght].ttf", true),
        new Entry(2014, "Yuji Hentaigana Akari", "ofl/yujihentaiganaakari/YujiHentaiganaAkari-Regular.ttf", true),
        new Entry(2015, "Yuyu Short", "ofl/yuyushort/YuyuShort-Regular.ttf", true),
        new Entry(2016, "Zain", "ofl/zain/Zain-Regular.ttf", true),
        new Entry(2017, "Zalando Sans", "ofl/zalandosans/ZalandoSans[wdth,wght].ttf", true),
        new Entry(2018, "Zalando Sans Semi Expanded", "ofl/zalandosanssemiexpanded/ZalandoSansSemiExpanded[wght].ttf", true),
        new Entry(2019, "ZCOOL Kuai Le", "ofl/zcoolkuaile/ZCOOLKuaiLe-Regular.ttf", true),
        new Entry(2020, "Zen Kaku Gothic New", "ofl/zenkakugothicnew/ZenKakuGothicNew-Regular.ttf", true),
        new Entry(2021, "Zen Loop", "ofl/zenloop/ZenLoop-Regular.ttf", true),
        new Entry(2022, "Zen Maru Gothic", "ofl/zenmarugothic/ZenMaruGothic-Regular.ttf", true),
        new Entry(2023, "Zhi Mang Xing", "ofl/zhimangxing/ZhiMangXing-Regular.ttf", true),
    };

    static Entry find(int style) {
        int index = style - FIRST_STYLE;
        if (index < 0 || index >= ITEMS.length) return null;
        return ITEMS[index];
    }

    private RemoteFontCatalog() {}
}
